# Generated by Django 4.2.4 on 2023-08-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkingWaterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_report_no', models.CharField(max_length=50)),
                ('invoice_bill_no', models.CharField(max_length=50)),
                ('reporting_date', models.DateField()),
                ('report_to', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('attention', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sample_id', models.CharField(max_length=30)),
                ('sample_collection_date', models.DateField()),
                ('sample_description', models.CharField(max_length=300)),
                ('sample_type', models.CharField(max_length=100)),
                ('sample_collected_by', models.CharField(max_length=100)),
                ('date_of_analysis_from', models.DateField()),
                ('date_of_analysis_to', models.DateField()),
                ('test_description', models.CharField(max_length=500)),
            ],
        ),
    ]
