# Generated by Django 4.2.30 on 2026-07-12 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0006_historicalequipment_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegulatoryLimit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('standard', models.CharField(max_length=20)),
                ('limit_min', models.FloatField(blank=True, null=True)),
                ('limit_max', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical regulatory limit',
                'verbose_name_plural': 'historical regulatory limits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegulatoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('standard', models.CharField(max_length=20)),
                ('limit_min', models.FloatField(blank=True, null=True)),
                ('limit_max', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parameter', 'standard')},
            },
        ),
    ]
