# Generated by Django 4.2.4 on 2023-08-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0006_remove_drinkingwaterform_water_sr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='date_of_analysis_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='date_of_analysis_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='reporting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='sample_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
