# Generated by Django 4.2.30 on 2026-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0008_chemicalitem_chemicallot_inventorydoccontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorydoccontrol',
            name='module',
            field=models.CharField(default='chemicals', max_length=20),
        ),
        migrations.AddField(
            model_name='inventorydoccontrol',
            name='module',
            field=models.CharField(default='chemicals', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalinventorydoccontrol',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorydoccontrol',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventorydoccontrol',
            unique_together={('module', 'location')},
        ),
    ]
