# Generated by Django 4.2.30 on 2026-07-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0009_historicalinventorydoccontrol_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lab',
            field=models.CharField(default='Karachi', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='lab',
            field=models.CharField(default='Karachi', max_length=20),
        ),
    ]
