# Generated by Django 4.2.4 on 2023-08-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0009_drinkingwaterform_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterform',
            name='analyzed_by',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='approved_by',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custom_legend',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='doc_controll_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='doc_controll_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='doc_controll_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='edit_note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_13',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_14',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='legend_9',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='reviewed_by',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
