# Generated by Django 4.2.30 on 2026-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EnviTechAlApp", "0012_dw_hist_textfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnoiseanalysis",
            name="custom_limit",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="noiseanalysis",
            name="custom_limit",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
