# Generated by Django 4.2.4 on 2023-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0014_alter_gaseousemissionform_gaseem_sr1'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaseousemissionform',
            name='GaseEm_conclusion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
