# Generated by Django 4.2.4 on 2023-08-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0015_gaseousemissionform_gaseem_conclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='GasEm_sr23',
        ),
    ]
