# Generated by Django 4.2.30 on 2026-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EnviTechAlApp", "0015_ww2_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnoisemonitoring",
            name="custom_limit",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="noisemonitoring",
            name="custom_limit",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
