# Generated by Django 4.2.30 on 2026-07-23 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0016_historicalnoisemonitoring_custom_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore')], default='Karachi', max_length=20)),
                ('month', models.CharField(blank=True, default='', max_length=30)),
                ('reagent_name', models.CharField(max_length=200)),
                ('reagent_no', models.CharField(blank=True, default='', max_length=40)),
                ('rtype', models.CharField(choices=[('Reagent', 'Reagent'), ('Standard', 'Standard'), ('Standardised titrant', 'Standardised titrant'), ('Buffer', 'Buffer'), ('% solution', '% solution')], default='Reagent', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('final_volume', models.CharField(blank=True, default='', max_length=40)),
                ('conc_value', models.CharField(blank=True, default='', max_length=40)),
                ('conc_unit', models.CharField(blank=True, default='', max_length=20)),
                ('prepared_by', models.CharField(blank=True, default='', max_length=120)),
                ('verified_by', models.CharField(blank=True, default='', max_length=120)),
                ('dop', models.DateField(blank=True, null=True)),
                ('doe', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReagentStandardisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Karachi', max_length=20)),
                ('primary_std', models.CharField(blank=True, default='', max_length=120)),
                ('ps_mass', models.FloatField(blank=True, null=True)),
                ('ps_purity', models.FloatField(blank=True, null=True)),
                ('ps_eqwt', models.FloatField(blank=True, null=True)),
                ('titrant_ml', models.FloatField(blank=True, null=True)),
                ('nominal_N', models.FloatField(blank=True, null=True)),
                ('true_N', models.FloatField(blank=True, null=True)),
                ('factor', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='N', max_length=10)),
                ('std_date', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('prep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standardisation', to='EnviTechAlApp.reagentprep')),
            ],
        ),
        migrations.CreateModel(
            name='ReagentPrepChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=1)),
                ('chemical_name', models.CharField(max_length=200)),
                ('cat_no', models.CharField(blank=True, default='', max_length=80)),
                ('lot_no', models.CharField(blank=True, default='', max_length=80)),
                ('quantity', models.CharField(blank=True, default='', max_length=60)),
                ('make', models.CharField(blank=True, default='', max_length=120)),
                ('expiry', models.CharField(blank=True, default='', max_length=40)),
                ('chemical_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='EnviTechAlApp.chemicallot')),
                ('prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='EnviTechAlApp.reagentprep')),
            ],
            options={
                'ordering': ['s_no', 'id'],
            },
        ),
    ]
