# Generated by Django 4.2.30 on 2026-07-23 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0017_reagentprep_reagentstandardisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentprep',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reagentprep',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagentprep',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReagentPrepAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='updated', max_length=30)),
                ('changed', models.TextField(blank=True, default='')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='EnviTechAlApp.reagentprep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
            },
        ),
    ]
