# Generated by Django 4.2.4 on 2023-08-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0018_rename_gasem_legend_1_gaseousemissionform_gaseem_legend_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_1',
            new_name='GaseEm_legend_1',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_10',
            new_name='GaseEm_legend_10',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_11',
            new_name='GaseEm_legend_11',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_12',
            new_name='GaseEm_legend_12',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_13',
            new_name='GaseEm_legend_13',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_14',
            new_name='GaseEm_legend_14',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_2',
            new_name='GaseEm_legend_2',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_3',
            new_name='GaseEm_legend_3',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_4',
            new_name='GaseEm_legend_4',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_5',
            new_name='GaseEm_legend_5',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_6',
            new_name='GaseEm_legend_6',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_7',
            new_name='GaseEm_legend_7',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_8',
            new_name='GaseEm_legend_8',
        ),
        migrations.RenameField(
            model_name='gaseousemissionform',
            old_name='GaseEm_Legend_9',
            new_name='GaseEm_legend_9',
        ),
    ]
