# Generated by Django 4.2.30 on 2026-07-24 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0018_reagentprep_updated_by_reagentprep_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentStandardisationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=40)),
                ('primary_std', models.CharField(blank=True, default='', max_length=120)),
                ('ps_mass', models.FloatField(blank=True, null=True)),
                ('ps_purity', models.FloatField(blank=True, null=True)),
                ('ps_eqwt', models.FloatField(blank=True, null=True)),
                ('titrant_ml', models.FloatField(blank=True, null=True)),
                ('nominal_N', models.FloatField(blank=True, null=True)),
                ('true_N', models.FloatField(blank=True, null=True)),
                ('factor', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='N', max_length=10)),
                ('std_date', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_history', to='EnviTechAlApp.reagentprep')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
