# Generated by Django 4.2.30 on 2026-07-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0019_reagentstandardisationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentstandardisation',
            name='aliquot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagentstandardisation',
            name='vol_made',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagentstandardisationhistory',
            name='aliquot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagentstandardisationhistory',
            name='vol_made',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
