# Generated by Django 4.2.4 on 2023-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0019_rename_gaseem_legend_1_gaseousemissionform_gaseem_legend_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientAirForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambienAir_lab_report_no1', models.CharField(max_length=50)),
                ('ambienAir_invoice_bill_no', models.CharField(max_length=50)),
                ('ambientAir_reporting_date', models.DateField(blank=True, null=True)),
                ('ambientAir_reporting_to', models.CharField(max_length=50)),
                ('ambientAir_address', models.CharField(max_length=100)),
                ('ambientAir_attention', models.CharField(max_length=100)),
                ('ambientAir_email', models.CharField(max_length=100)),
                ('ambientAir_test_id', models.CharField(max_length=30)),
                ('ambientAir_test_perf_date', models.CharField(max_length=40)),
                ('ambientAir_test_type_location', models.CharField(max_length=300)),
                ('ambientAir_test_perf_by', models.CharField(max_length=100)),
                ('ambienAir_test_desc', models.CharField(max_length=100)),
                ('ambientAir_sr1', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr2', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr3', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr4', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr5', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr6', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr7', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr8', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr9', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr10', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr11', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr12', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr13', models.CharField(max_length=50, null=True)),
                ('ambientAir_sr14', models.CharField(max_length=50, null=True)),
                ('ambientAir_conclusion', models.CharField(max_length=50, null=True)),
                ('ambientAir_legend_1', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_2', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_3', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_4', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_5', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_6', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_7', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_8', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_9', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_10', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_11', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_12', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_13', models.CharField(max_length=100, null=True)),
                ('ambientAir_legend_14', models.CharField(max_length=100, null=True)),
                ('ambientAir_edit_note', models.CharField(max_length=100, null=True)),
                ('ambientAir_custom_legend', models.CharField(max_length=100, null=True)),
                ('ambientAir_doc_con_1', models.CharField(max_length=100, null=True)),
                ('ambientAir_doc_con_2', models.CharField(max_length=100, null=True)),
                ('ambientAir_doc_con_3', models.CharField(max_length=100, null=True)),
                ('ambientAir_analyzed_by', models.ImageField(default='', upload_to='')),
                ('ambientAir_reviewd_by', models.ImageField(default='', upload_to='')),
                ('ambientAir_approved_by', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
