# Generated by Django 4.2.4 on 2023-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0020_ambientairform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteWaterSludge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ww_lab_report_no', models.CharField(max_length=50)),
                ('ww_invoice_no', models.CharField(max_length=50)),
                ('ww_report_date', models.CharField(max_length=50)),
                ('ww_report_to', models.CharField(max_length=50)),
                ('ww_address', models.CharField(max_length=50)),
                ('ww_attention', models.CharField(max_length=50)),
                ('ww_email', models.CharField(max_length=50)),
                ('ww_sampleid', models.CharField(max_length=50)),
                ('ww_sample_colec_Date', models.CharField(max_length=50)),
                ('ww_sample_desc', models.CharField(max_length=50)),
                ('ww_sample_type', models.CharField(max_length=50)),
                ('ww_sample_colec_by', models.CharField(max_length=50)),
                ('ww_date_of_analy', models.CharField(max_length=50)),
                ('ww_test_desc', models.CharField(max_length=50)),
                ('ww_sr1', models.CharField(max_length=50)),
                ('ww_sr2', models.CharField(max_length=50)),
                ('ww_sr3', models.CharField(max_length=50)),
                ('ww_sr4', models.CharField(max_length=50)),
                ('ww_sr5', models.CharField(max_length=50)),
                ('ww_sr6', models.CharField(max_length=50)),
                ('ww_sr7', models.CharField(max_length=50)),
                ('ww_sr8', models.CharField(max_length=50)),
                ('ww_sr9', models.CharField(max_length=50)),
                ('ww_sr10', models.CharField(max_length=50)),
                ('ww_sr11', models.CharField(max_length=50)),
                ('ww_sr12', models.CharField(max_length=50)),
                ('ww_sr13', models.CharField(max_length=50)),
                ('ww_sr14', models.CharField(max_length=50)),
                ('ww_conclusion', models.CharField(max_length=50)),
                ('ww_legend_1', models.CharField(max_length=50)),
                ('ww_legend_2', models.CharField(max_length=50)),
                ('ww_legend_3', models.CharField(max_length=50)),
                ('ww_legend_4', models.CharField(max_length=50)),
                ('ww_legend_5', models.CharField(max_length=50)),
                ('ww_legend_6', models.CharField(max_length=50)),
                ('ww_legend_7', models.CharField(max_length=50)),
                ('ww_legend_8', models.CharField(max_length=50)),
                ('ww_legend_9', models.CharField(max_length=50)),
                ('ww_legend_10', models.CharField(max_length=50)),
                ('ww_legend_11', models.CharField(max_length=50)),
                ('ww_legend_12', models.CharField(max_length=50)),
                ('ww_legend_13', models.CharField(max_length=50)),
                ('ww_legend_14', models.CharField(max_length=50)),
                ('ww_editnote', models.CharField(max_length=50)),
                ('ww_custom_legend', models.CharField(max_length=50)),
                ('ww_doc_con_1', models.CharField(max_length=50)),
                ('ww_doc_con_2', models.CharField(max_length=50)),
                ('ww_doc_con_3', models.CharField(max_length=50)),
                ('ww_analyzed_by', models.ImageField(default='', upload_to='')),
                ('ww_reviewd_by', models.ImageField(default='', upload_to='')),
                ('ww_approved_by', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
