# Generated by Django 4.2.30 on 2026-07-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0021_chemicallot_cat_no_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalchemicallot',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalchemicallot',
            name='cat_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
