# Generated by Django 4.2.4 on 2023-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0022_remove_wastewatersludge_ww_sr14'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculEmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehEm_lab_report_no', models.CharField(max_length=50)),
                ('vehEm_invoice_no', models.CharField(max_length=50)),
                ('vehEm_report_date', models.CharField(max_length=50)),
                ('vehEm_address', models.CharField(max_length=50)),
                ('vehEm_attention', models.CharField(max_length=50)),
                ('vehEm_email', models.CharField(max_length=50)),
                ('vehEm_testId', models.CharField(max_length=50)),
                ('vehEm_test_perf_date', models.CharField(max_length=50)),
                ('vehEm_test_type', models.CharField(max_length=50)),
                ('vehEm_test_perfBy', models.CharField(max_length=50)),
                ('vehEm_test_desc', models.CharField(max_length=50)),
                ('venEm_sr1', models.CharField(max_length=50)),
                ('venEm_sr2', models.CharField(max_length=50)),
                ('venEm_sr3', models.CharField(max_length=50)),
                ('vehEm_concl', models.CharField(max_length=50)),
                ('vehEm_legend_1', models.CharField(max_length=50)),
                ('vehEm_legend_2', models.CharField(max_length=50)),
                ('vehEm_legend_3', models.CharField(max_length=50)),
                ('vehEm_legend_4', models.CharField(max_length=50)),
                ('vehEm_legend_5', models.CharField(max_length=50)),
                ('vehEm_legend_6', models.CharField(max_length=50)),
                ('vehEm_legend_7', models.CharField(max_length=50)),
                ('vehEm_legend_8', models.CharField(max_length=50)),
                ('vehEm_legend_9', models.CharField(max_length=50)),
                ('vehEm_legend_10', models.CharField(max_length=50)),
                ('vehEm_legend_11', models.CharField(max_length=50)),
                ('vehEm_legend_12', models.CharField(max_length=50)),
                ('vehEm_legend_13', models.CharField(max_length=50)),
                ('vehEm_legend_14', models.CharField(max_length=50)),
                ('vehEm_edit_note', models.CharField(max_length=50)),
                ('vehEm_custom_legend', models.CharField(max_length=50)),
                ('vehEm_doc_con1', models.CharField(max_length=50)),
                ('vehEm_doc_con2', models.CharField(max_length=50)),
                ('vehEm_doc_con3', models.CharField(max_length=50)),
                ('vehEm_analyzedby', models.ImageField(default='', upload_to='')),
                ('vehEm_reviewedby', models.ImageField(default='', upload_to='')),
                ('vehEm_approvedby', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
