# Generated by Django 4.2.30 on 2026-07-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0022_historicalchemicallot_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='col_unit_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='neqs_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='peqs_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='seqs_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalambientair2',
            name='col_unit_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalgaseousemissionform',
            name='neqs_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgaseousemissionform',
            name='peqs_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgaseousemissionform',
            name='seqs_limits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
