# Generated by Django 4.2.4 on 2023-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0023_vehiculemissionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculemissionform',
            name='vehEm_report_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
