# Generated by Django 4.2.30 on 2026-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0023_ambientair2_col_unit_1_ambientair2_col_unit_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnoiseanalysis',
            name='row_limits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='row_limits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
