# Generated by Django 4.2.4 on 2023-08-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0024_vehiculemissionform_vehem_report_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculemissionform',
            old_name='venEm_sr1',
            new_name='vehEm_sr1',
        ),
        migrations.RenameField(
            model_name='vehiculemissionform',
            old_name='venEm_sr2',
            new_name='vehEm_sr2',
        ),
        migrations.RenameField(
            model_name='vehiculemissionform',
            old_name='venEm_sr3',
            new_name='vehEm_sr3',
        ),
    ]
