# Generated by Django 4.1.1 on 2026-07-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0024_historicalnoiseanalysis_row_limits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentprep',
            name='rtype',
            field=models.CharField(choices=[('Reagent', 'Reagent'), ('Standard', 'Standard'), ('Multi-component reagent', 'Multi-component reagent'), ('Standardised titrant', 'Standardised titrant'), ('Buffer', 'Buffer'), ('% solution', '% solution')], default='Reagent', max_length=30),
        ),
    ]
