# Generated by Django 4.2.30 on 2026-07-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0026_ppwranalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppwranalysis',
            name='ppwr_legend_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ppwranalysis',
            name='ppwr_legend_4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ppwranalysis',
            name='ppwr_legend_5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
