# Generated by Django 5.2.16 on 2026-08-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EnviTechAlApp", "0027_ppwranalysis_ppwr_legend_3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ppwranalysis",
            name="ppwr_custom_legend",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
