# Generated by Django 4.2.4 on 2023-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0027_packingpolybagform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineOilForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_lab_rep_no', models.CharField(max_length=50)),
                ('machine_invoice_no', models.CharField(max_length=50)),
                ('machine_rep_date', models.CharField(max_length=50)),
                ('machine_report_to', models.CharField(max_length=50)),
                ('machine_address', models.CharField(max_length=50)),
                ('machine_attention', models.CharField(max_length=50)),
                ('machine_email', models.CharField(max_length=50)),
                ('machine_sampleId', models.CharField(max_length=50)),
                ('machine_sample_col_date', models.CharField(max_length=50)),
                ('machine_sample_desc', models.CharField(max_length=50)),
                ('machine_sample_type', models.CharField(max_length=50)),
                ('machine_sample_col_by', models.CharField(max_length=50)),
                ('machine_test_desc', models.CharField(max_length=50)),
                ('machine_sr1', models.CharField(max_length=50)),
                ('machine_sr2', models.CharField(max_length=50)),
                ('machine_sr3', models.CharField(max_length=50)),
                ('machine_sr4', models.CharField(max_length=50)),
                ('machine_sr5', models.CharField(max_length=50)),
                ('machine_sr6', models.CharField(max_length=50)),
                ('machine_sr7', models.CharField(max_length=50)),
                ('machine_sr8', models.CharField(max_length=50)),
                ('machine_sr9', models.CharField(max_length=50)),
                ('machine_sr10', models.CharField(max_length=50)),
                ('machine_sr11', models.CharField(max_length=50)),
                ('machine_sr12', models.CharField(max_length=50)),
                ('machine_sr13', models.CharField(max_length=50)),
                ('machine_sr14', models.CharField(max_length=50)),
                ('machine_sr15', models.CharField(max_length=50)),
                ('machine_sr16', models.CharField(max_length=50)),
                ('machine_conl', models.CharField(max_length=50)),
                ('machine_legend_1', models.CharField(max_length=50)),
                ('machine_legend_2', models.CharField(max_length=50)),
                ('machine_legend_3', models.CharField(max_length=50)),
                ('machine_legend_4', models.CharField(max_length=50)),
                ('machine_legend_5', models.CharField(max_length=50)),
                ('machine_legend_6', models.CharField(max_length=50)),
                ('machine_legend_7', models.CharField(max_length=50)),
                ('machine_legend_8', models.CharField(max_length=50)),
                ('machine_legend_9', models.CharField(max_length=50)),
                ('machine_legend_10', models.CharField(max_length=50)),
                ('machine_legend_11', models.CharField(max_length=50)),
                ('machine_legend_12', models.CharField(max_length=50)),
                ('machine_legend_13', models.CharField(max_length=50)),
                ('machine_legend_14', models.CharField(max_length=50)),
                ('machine_edit_note', models.CharField(max_length=50)),
                ('machine_custom_legend', models.CharField(max_length=50)),
                ('machine_doc1', models.CharField(max_length=50)),
                ('machine_doc2', models.CharField(max_length=50)),
                ('machine_doc3', models.CharField(max_length=50)),
                ('machine_analyzedby', models.ImageField(max_length=50, upload_to='')),
                ('machine_reviewedby', models.ImageField(max_length=50, upload_to='')),
                ('machine_approvedby', models.ImageField(max_length=50, upload_to='')),
            ],
        ),
    ]
