# Generated by Django 4.2.4 on 2023-09-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0028_machineoilform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_lab_report_no', models.CharField(max_length=50)),
                ('micro_invoice_bill', models.CharField(max_length=50)),
                ('micro_rep_date', models.CharField(max_length=50)),
                ('micro_rep_to', models.CharField(max_length=50)),
                ('micro_address', models.CharField(max_length=50)),
                ('micro_attention', models.CharField(max_length=50)),
                ('micro_email', models.CharField(max_length=50)),
                ('micro_sampleId', models.CharField(max_length=50)),
                ('micro_sample_col_date', models.CharField(max_length=50)),
                ('micro_sample_desc', models.CharField(max_length=50)),
                ('micro_sample_type', models.CharField(max_length=50)),
                ('micro_sample_col_by', models.CharField(max_length=50)),
                ('micro_date_analysis', models.CharField(max_length=50)),
                ('micro_test_desc', models.CharField(max_length=50)),
                ('micro_sr1', models.CharField(max_length=50)),
                ('micro_sr2', models.CharField(max_length=50)),
                ('micro_sr3', models.CharField(max_length=50)),
                ('micro_sr4', models.CharField(max_length=50)),
                ('micro_sr5', models.CharField(max_length=50)),
                ('micro_sr6', models.CharField(max_length=50)),
                ('micro_concl', models.CharField(max_length=50)),
                ('micro_legend_1', models.CharField(max_length=50)),
                ('micro_legend_2', models.CharField(max_length=50)),
                ('micro_legend_3', models.CharField(max_length=50)),
                ('micro_legend_4', models.CharField(max_length=50)),
                ('micro_legend_5', models.CharField(max_length=50)),
                ('micro_legend_6', models.CharField(max_length=50)),
                ('micro_legend_7', models.CharField(max_length=50)),
                ('micro_legend_8', models.CharField(max_length=50)),
                ('micro_legend_9', models.CharField(max_length=50)),
                ('micro_legend_10', models.CharField(max_length=50)),
                ('micro_legend_11', models.CharField(max_length=50)),
                ('micro_legend_12', models.CharField(max_length=50)),
                ('micro_legend_13', models.CharField(max_length=50)),
                ('micro_legend_14', models.CharField(max_length=50)),
                ('micro_editnote', models.CharField(max_length=50)),
                ('micro_custom_legend', models.CharField(max_length=50)),
                ('micro_doc1', models.CharField(max_length=50)),
                ('micro_doc2', models.CharField(max_length=50)),
                ('micro_doc3', models.CharField(max_length=50)),
                ('micro_analyzedby', models.ImageField(default='', upload_to='')),
                ('micro_reviewedby', models.ImageField(default='', upload_to='')),
                ('micro_approvedby', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
