# Generated by Django 4.2.4 on 2023-09-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0029_microbialanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViscousLiquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_rep_no', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(max_length=50)),
                ('report_date', models.CharField(max_length=50)),
                ('report_to', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('Attention', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('sampleId', models.CharField(max_length=50)),
                ('sample_Col_date', models.CharField(max_length=50)),
                ('sample_Desc', models.CharField(max_length=50)),
                ('sample_type', models.CharField(max_length=50)),
                ('sample_col_by', models.CharField(max_length=50)),
                ('date_of_analysis', models.CharField(max_length=50)),
                ('test_desc', models.CharField(max_length=50)),
                ('viscous_select', models.CharField(max_length=50)),
                ('sr1', models.CharField(max_length=50)),
                ('concl', models.CharField(max_length=50)),
                ('legend_1', models.CharField(max_length=50)),
                ('legend_2', models.CharField(max_length=50)),
                ('legend_3', models.CharField(max_length=50)),
                ('legend_4', models.CharField(max_length=50)),
                ('legend_5', models.CharField(max_length=50)),
                ('legend_6', models.CharField(max_length=50)),
                ('legend_7', models.CharField(max_length=50)),
                ('legend_8', models.CharField(max_length=50)),
                ('legend_9', models.CharField(max_length=50)),
                ('legend_10', models.CharField(max_length=50)),
                ('legend_11', models.CharField(max_length=50)),
                ('legend_12', models.CharField(max_length=50)),
                ('legend_13', models.CharField(max_length=50)),
                ('legend_14', models.CharField(max_length=50)),
                ('edit_note', models.CharField(max_length=50)),
                ('custom_legend', models.CharField(max_length=50)),
                ('doc1', models.CharField(max_length=50)),
                ('doc2', models.CharField(max_length=50)),
                ('doc3', models.CharField(max_length=50)),
                ('analyzedby', models.ImageField(max_length=50, upload_to='')),
                ('reviewedby', models.ImageField(max_length=50, upload_to='')),
                ('approvedby', models.ImageField(max_length=50, upload_to='')),
            ],
        ),
    ]
