# Generated by Django 4.2.4 on 2023-09-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0031_ambientair2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientair2',
            name='sr10_10',
        ),
    ]
