# Generated by Django 4.2.4 on 2023-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0034_noiseanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='id',
            field=models.UUIDField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
