# Generated by Django 4.2.4 on 2023-09-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0036_alter_ambientair2_id_alter_ambientairform_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkingwaterform',
            name='legend_12',
        ),
        migrations.RemoveField(
            model_name='drinkingwaterform',
            name='legend_13',
        ),
        migrations.RemoveField(
            model_name='drinkingwaterform',
            name='legend_14',
        ),
    ]
