# Generated by Django 4.2.4 on 2023-09-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0037_remove_drinkingwaterform_legend_12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkingwaterform',
            name='conclusion',
        ),
    ]
