# Generated by Django 4.2.4 on 2023-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0039_drinkingwaterform_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterform',
            name='approved_by1',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
