# Generated by Django 4.2.4 on 2023-09-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0040_drinkingwaterform_approved_by1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='GaseEm_conclusion',
        ),
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='GaseEm_legend_12',
        ),
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='GaseEm_legend_13',
        ),
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='GaseEm_legend_14',
        ),
    ]
