# Generated by Django 4.2.4 on 2023-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0041_remove_gaseousemissionform_gaseem_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaseousemissionform',
            name='GaseEm_reporting_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
