# Generated by Django 4.2.4 on 2023-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0043_gaseousemissionform_gaseem_approved_by1'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaseousemissionform',
            name='GaseEm_select',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
