# Generated by Django 4.2.4 on 2023-09-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0047_alter_ambientairform_ambientair_reporting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientairform',
            name='ambienAir_select',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
