# Generated by Django 4.2.4 on 2023-09-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0048_ambientairform_ambienair_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientairform',
            name='ambientAir_legend_10',
        ),
        migrations.RemoveField(
            model_name='ambientairform',
            name='ambientAir_legend_11',
        ),
        migrations.RemoveField(
            model_name='ambientairform',
            name='ambientAir_legend_7',
        ),
        migrations.RemoveField(
            model_name='ambientairform',
            name='ambientAir_legend_8',
        ),
        migrations.RemoveField(
            model_name='ambientairform',
            name='ambientAir_legend_9',
        ),
    ]
