# Generated by Django 4.2.4 on 2023-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0049_remove_ambientairform_ambientair_legend_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='ww_conclusion',
        ),
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='ww_legend_12',
        ),
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='ww_legend_13',
        ),
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='ww_legend_14',
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_approved_by1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
