# Generated by Django 4.2.4 on 2023-09-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0050_remove_wastewatersludge_ww_conclusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculemissionform',
            name='vehEm_edit_note',
        ),
        migrations.RemoveField(
            model_name='vehiculemissionform',
            name='vehEm_legend_12',
        ),
        migrations.RemoveField(
            model_name='vehiculemissionform',
            name='vehEm_legend_13',
        ),
        migrations.RemoveField(
            model_name='vehiculemissionform',
            name='vehEm_legend_14',
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='select',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
