# Generated by Django 4.2.4 on 2023-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0051_remove_vehiculemissionform_vehem_edit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculemissionform',
            name='vehEm_approvedby1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
