# Generated by Django 4.2.4 on 2023-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0052_vehiculemissionform_vehem_approvedby1'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculemissionform',
            name='vehEm_edit_note',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
