# Generated by Django 4.2.4 on 2023-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0054_remove_vehiculemissionform_vehem_concl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_concl',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_12',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_13',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_14',
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_approvedby1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
