# Generated by Django 4.2.4 on 2023-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0055_remove_luxanalysisform_lux_concl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_10',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_11',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_2',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_3',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_4',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_5',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_6',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_7',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_8',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='lux_legend_9',
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pack_approved_by1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
