# Generated by Django 4.2.4 on 2023-09-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0056_remove_luxanalysisform_lux_legend_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_10',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_11',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_12',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_13',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_14',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_2',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_3',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_4',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_5',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_6',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_7',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_8',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='pack_legend_9',
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lux_legend_9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='luxanalysisform',
            name='lux_edit_note',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='luxanalysisform',
            name='lux_legend_1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
