# Generated by Django 4.2.4 on 2023-09-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0057_remove_packingpolybagform_pack_legend_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noiseanalysis',
            name='concl',
        ),
        migrations.RemoveField(
            model_name='noiseanalysis',
            name='legend_12',
        ),
        migrations.RemoveField(
            model_name='noiseanalysis',
            name='legend_13',
        ),
        migrations.RemoveField(
            model_name='noiseanalysis',
            name='legend_14',
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='machine_approvedby1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='approvedby1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
