# Generated by Django 4.2.4 on 2023-09-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0059_noiseanalysis_select1_alter_noiseanalysis_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_10',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_11',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_12',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_13',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_14',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_3',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_4',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_5',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_6',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_7',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_8',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_legend_9',
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='custom_legend',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
