# Generated by Django 4.2.4 on 2023-09-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0060_remove_machineoilform_machine_legend_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineoilform',
            name='machine_conl',
        ),
    ]
