# Generated by Django 4.2.4 on 2023-09-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0064_remove_ambientair2_concl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='sr1_8',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
