# Generated by Django 4.2.4 on 2023-10-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0074_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxanalysisform',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
