# Generated by Django 4.1.1 on 2023-10-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0076_ambientair2_location_ambientairform_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microbialanalysis',
            name='micro_date_analysis',
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_date_analysis_from',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_date_analysis_to',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
