# Generated by Django 4.1.1 on 2023-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0077_remove_microbialanalysis_micro_date_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastewaterform2',
            name='date_of_analysis',
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='date_of_analysis_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='date_of_analysis_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
