# Generated by Django 4.1.1 on 2023-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0078_remove_wastewaterform2_date_of_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewaterform2',
            name='in_out',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
