# Generated by Django 4.1.1 on 2023-10-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0079_wastewaterform2_in_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viscousliquid',
            name='date_of_analysis',
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='date_of_analysis_from',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='date_of_analysis_to',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
