# Generated by Django 4.1.1 on 2023-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0080_remove_viscousliquid_date_of_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='ww_date_of_analy',
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_date_of_analy_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_date_of_analy_to',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='zdhc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
