# Generated by Django 4.1.1 on 2023-10-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0081_remove_wastewatersludge_ww_date_of_analy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_sr14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_sr15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_sr16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='ww_sr17',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
