# Generated by Django 4.1.1 on 2023-10-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0082_wastewatersludge_ww_sr14_wastewatersludge_ww_sr15_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='method_checkBox',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
