# Generated by Django 4.1.1 on 2023-10-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0083_ambientair2_method_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='hours_checkBox',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
