# Generated by Django 4.1.1 on 2023-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0085_wastewaterform2_inlet_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterform',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
    ]
