# Generated by Django 4.1.1 on 2023-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0086_drinkingwaterform_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewaterform2',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
    ]
