# Generated by Django 4.1.1 on 2023-10-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0087_wastewaterform2_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewaterform2',
            name='customLimits',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
