# Generated by Django 4.1.1 on 2023-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0089_wastewaterform2_cutomlimit1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastewaterform2',
            name='customLimits',
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit19',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit20',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit29',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit30',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit33',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='cutomLimit9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
