# Generated by Django 4.1.1 on 2023-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0090_remove_wastewaterform2_customlimits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewaterform2',
            name='customLimit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
