# Generated by Django 4.1.1 on 2023-10-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0091_wastewaterform2_customlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastewaterform2',
            name='customLimit',
        ),
    ]
