# Generated by Django 4.1.1 on 2023-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0092_remove_wastewaterform2_customlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput13',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput14',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput15',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput16',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput17',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput18',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput19',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput21',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput22',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput23',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput24',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput25',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput26',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput27',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput28',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput29',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput30',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput31',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput32',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='custominput9',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='in_out',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
