# Generated by Django 4.1.1 on 2023-11-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0094_historicaldrinkingwaterform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDrinkingWaterForm',
        ),
    ]
