# Generated by Django 4.1.1 on 2023-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0095_delete_historicaldrinkingwaterform'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientairform',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
    ]
