# Generated by Django 4.1.1 on 2023-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0097_rename_invoice_no_ambientair2_invoice_bill_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='city_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
