# Generated by Django 4.1.1 on 2023-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0098_ambientair2_city_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='report_type',
            field=models.CharField(default='aa2', max_length=50),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='report_type',
            field=models.CharField(default='aa', max_length=50),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='report_type',
            field=models.CharField(default='dw', max_length=50),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='report_type',
            field=models.CharField(default='gae', max_length=50),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='report_type',
            field=models.CharField(default='la', max_length=50),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='report_type',
            field=models.CharField(default='mo', max_length=50),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='report_type',
            field=models.CharField(default='ma', max_length=50),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='report_type',
            field=models.CharField(default='na', max_length=50),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='report_type',
            field=models.CharField(default='pp', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='report_type',
            field=models.CharField(default='ve', max_length=50),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='report_type',
            field=models.CharField(default='vl', max_length=50),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='report_type',
            field=models.CharField(default='ww2', max_length=50),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='report_type',
            field=models.CharField(default='ww', max_length=50),
        ),
    ]
