# Generated by Django 4.1.1 on 2023-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0100_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cert_num', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('insp_date', models.CharField(max_length=200)),
                ('equipment', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('equip_id', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('equipment_1', models.CharField(max_length=200)),
                ('model_1', models.CharField(max_length=200)),
                ('serial_no1', models.CharField(max_length=200)),
                ('cert_num1', models.CharField(max_length=200)),
                ('test1', models.CharField(max_length=200)),
                ('test2', models.CharField(max_length=200)),
                ('test3', models.CharField(max_length=200)),
                ('test4', models.CharField(max_length=200)),
                ('test5', models.CharField(max_length=200)),
                ('test6', models.CharField(max_length=200)),
                ('test7', models.CharField(max_length=200)),
                ('test8', models.CharField(max_length=200)),
                ('test9', models.CharField(max_length=200)),
                ('test10', models.CharField(max_length=200)),
                ('conc', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('calib_by', models.ImageField(max_length=50, upload_to='')),
                ('checked', models.ImageField(max_length=50, upload_to='')),
                ('checked1', models.ImageField(max_length=50, upload_to='')),
                ('disc', models.CharField(max_length=200)),
                ('extra_field', models.TextField(default=[])),
            ],
        ),
    ]
