# Generated by Django 4.1.1 on 2023-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0102_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='insp_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
