# Generated by Django 4.1.1 on 2023-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0103_inspection_insp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='re_insp_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
