# Generated by Django 4.1.1 on 2023-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0104_inspection_re_insp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_1_7',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_ex_2_7',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='micro_p7',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
