# Generated by Django 4.1.1 on 2023-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0105_microbialanalysis_micro_ex_1_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='extra_field1',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='calibration',
            name='extra_field2',
            field=models.TextField(default=[]),
        ),
    ]
