# Generated by Django 4.1.1 on 2023-12-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0106_calibration_extra_field1_calibration_extra_field2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleId', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('name_of_person', models.CharField(max_length=50)),
                ('contact_detail', models.CharField(max_length=50)),
                ('nature_of_sample', models.CharField(max_length=50)),
                ('recieving_date', models.CharField(max_length=50)),
                ('expected_reported', models.CharField(max_length=50)),
                ('recieved_by', models.CharField(max_length=50)),
            ],
        ),
    ]
