# Generated by Django 4.1.1 on 2023-12-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0107_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='extra_field1',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='verification',
            name='extra_field1',
            field=models.TextField(default=[]),
        ),
    ]
