# Generated by Django 4.1.1 on 2023-12-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0110_sample_registration_inp79_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_registration',
            name='inp1',
        ),
        migrations.RemoveField(
            model_name='sample_registration',
            name='inp2',
        ),
        migrations.RemoveField(
            model_name='sample_registration',
            name='inp3',
        ),
    ]
