# Generated by Django 4.1.1 on 2023-12-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0112_sample_registration_checkinp_bacteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='inp1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp10',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp108',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp109',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp112',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp115',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp18',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp19',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp20',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp6',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp7',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp8',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp9',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
