# Generated by Django 4.1.1 on 2023-12-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0113_alter_sample_registration_inp1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='checkinp_bacteria',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='checkinp_chemical',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
