# Generated by Django 4.1.1 on 2023-12-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0117_alter_sample_registration_checkinp_bacteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='checkinp_bacteria',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='checkinp_chemical',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
