# Generated by Django 4.1.1 on 2023-12-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0118_alter_sample_registration_checkinp_bacteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='inp106',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp108',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='inp18',
            field=models.BooleanField(default=False),
        ),
    ]
