# Generated by Django 4.1.1 on 2023-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0119_alter_sample_registration_inp106_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='checkinp_bacteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='checkinp_chemical',
            field=models.BooleanField(default=False),
        ),
    ]
