# Generated by Django 4.1.1 on 2023-12-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0120_alter_sample_registration_checkinp_bacteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
