# Generated by Django 4.1.1 on 2023-12-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0121_alter_sample_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='issue_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='issue_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='lab_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='sample_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
