# Generated by Django 4.1.1 on 2023-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0123_rename_inp100_sample_registration_checkinp100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='city_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
