# Generated by Django 4.1.1 on 2023-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0124_sample_registration_city_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='assign_to',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
