# Generated by Django 4.1.1 on 2023-12-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0125_sample_registration_assign_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='date_calib',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='insp_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='verif_date',
            new_name='date',
        ),
    ]
