# Generated by Django 4.1.1 on 2023-12-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0126_rename_date_calib_calibration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='cert_type',
            field=models.CharField(default='calib', max_length=50),
        ),
        migrations.AddField(
            model_name='inspection',
            name='cert_type',
            field=models.CharField(default='insp', max_length=50),
        ),
        migrations.AddField(
            model_name='verification',
            name='cert_type',
            field=models.CharField(default='verif', max_length=50),
        ),
    ]
