# Generated by Django 4.1.1 on 2023-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0127_calibration_cert_type_inspection_cert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='city_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='city_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='city_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
