# Generated by Django 4.1.1 on 2023-12-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0132_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
