# Generated by Django 4.1.1 on 2023-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0133_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
