# Generated by Django 4.1.1 on 2023-12-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0134_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='conntrol_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='sampling_by',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
