# Generated by Django 4.1.1 on 2023-12-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0135_sample_registration_conntrol_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='conntrol_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='conntrol_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
