# Generated by Django 4.1.1 on 2023-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0136_sample_registration_conntrol_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_location', models.CharField(max_length=100)),
                ('sample_id', models.CharField(max_length=500)),
                ('client_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('att_person', models.CharField(max_length=500)),
                ('sample_nature', models.CharField(max_length=500)),
                ('rec_date', models.CharField(max_length=500)),
                ('exp_date', models.CharField(max_length=500)),
                ('rep_date', models.CharField(max_length=500)),
                ('rec_by', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
    ]
