# Generated by Django 4.1.1 on 2023-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0137_loggingsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingsheet',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
