# Generated by Django 4.1.1 on 2023-12-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0140_alter_loggingsheet_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='exp_date',
            field=models.DateField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loggingsheet',
            name='rec_date',
            field=models.DateField(max_length=500),
        ),
        migrations.AlterField(
            model_name='loggingsheet',
            name='rep_date',
            field=models.DateField(max_length=500),
        ),
    ]
