# Generated by Django 4.1.1 on 2023-12-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0141_alter_loggingsheet_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingsheet',
            name='month',
            field=models.DateField(max_length=500, null=True),
        ),
    ]
