# Generated by Django 4.1.1 on 2023-12-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0142_loggingsheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
