# Generated by Django 4.1.1 on 2023-12-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0143_alter_loggingsheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
