# Generated by Django 4.1.1 on 2023-12-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0147_alter_loggingsheet_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingsheet',
            name='issue',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='issue_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='issue_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='lab',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
