# Generated by Django 4.1.1 on 2023-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0148_loggingsheet_issue_loggingsheet_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.DateField(max_length=500, null=True),
        ),
    ]
