# Generated by Django 4.1.1 on 2023-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0149_alter_loggingsheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='exp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loggingsheet',
            name='rec_date',
            field=models.DateField(),
        ),
    ]
