# Generated by Django 4.1.1 on 2023-12-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0150_alter_loggingsheet_exp_date_alter_loggingsheet_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggingsheet',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='loggingsheet',
            name='month',
        ),
        migrations.RemoveField(
            model_name='loggingsheet',
            name='rec_date',
        ),
        migrations.RemoveField(
            model_name='loggingsheet',
            name='rep_date',
        ),
    ]
