# Generated by Django 4.1.1 on 2023-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0151_remove_loggingsheet_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingsheet',
            name='exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='month',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='rec_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='rep_date',
            field=models.DateField(null=True),
        ),
    ]
