# Generated by Django 4.1.1 on 2023-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0152_loggingsheet_exp_date_loggingsheet_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
