# Generated by Django 4.1.1 on 2023-12-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0153_alter_loggingsheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='exp_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loggingsheet',
            name='rec_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loggingsheet',
            name='rep_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
