# Generated by Django 4.1.1 on 2024-03-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0154_alter_loggingsheet_exp_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noiseanalysis',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
    ]
