# Generated by Django 4.1.1 on 2024-03-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0155_noiseanalysis_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxanalysisform',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
    ]
