# Generated by Django 4.1.1 on 2025-01-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0158_inspection_after1_inspection_after2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='client_equip_data',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='master_equip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='physical_inspect',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
