# Generated by Django 4.1.1 on 2025-02-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0159_inspection_client_equip_data_inspection_master_equip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='other1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='other2',
            field=models.BooleanField(default=False),
        ),
    ]
