# Generated by Django 4.1.1 on 2025-02-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0160_sample_registration_other1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='other1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
