# Generated by Django 4.1.1 on 2025-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0163_alter_sample_registration_assign_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='other1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
