# Generated by Django 4.1.1 on 2025-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0165_ambientair2_customer_id_ambientairform_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
