# Generated by Django 4.1.1 on 2025-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0166_alter_loggingsheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.DateField(null=True),
        ),
    ]
