# Generated by Django 4.1.1 on 2025-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0167_alter_loggingsheet_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingsheet',
            name='month',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
