# Generated by Django 4.1.1 on 2025-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0169_alter_loggingsheet_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_1',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_2',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_3',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_4',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_5',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_6',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_7',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_8',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='neqs_lim_9',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_1',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_2',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_3',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_4',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_5',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_6',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_7',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_8',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='peqs_lim_9',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_1',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_2',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_3',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_4',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_5',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_6',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_7',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_8',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='seqs_lim_9',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
