# Generated by Django 4.1.1 on 2025-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0170_ambientair2_neqs_lim_1_ambientair2_neqs_lim_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaseousemissionform',
            name='GasEm_test_type_extra',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
