# Generated by Django 4.1.1 on 2025-04-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0171_gaseousemissionform_gasem_test_type_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculemissionform',
            name='vehEm_test_type_extra',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
