# Generated by Django 4.1.1 on 2025-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0172_vehiculemissionform_vehem_test_type_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_by', models.ImageField(upload_to='')),
                ('reviewed_by', models.ImageField(upload_to='')),
                ('lab_manager', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
