# Generated by Django 4.1.1 on 2025-06-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0173_signatures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signatures',
        ),
    ]
