# Generated by Django 4.1.1 on 2025-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0175_alter_ambientair2_analyzedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientair2',
            name='analyzedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientair2',
            name='approvedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientair2',
            name='approvedby1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientair2',
            name='reviewedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientairform',
            name='ambientAir_analyzed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientairform',
            name='ambientAir_approved_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientairform',
            name='ambientAir_approved_by1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ambientairform',
            name='ambientAir_reviewd_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='calib_by',
            field=models.ImageField(default='', max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='checked',
            field=models.ImageField(default='', max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='checked1',
            field=models.ImageField(default='', max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='analyzed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='approved_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='approved_by1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='reviewed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gaseousemissionform',
            name='GaseEm_analyzed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gaseousemissionform',
            name='GaseEm_approved_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gaseousemissionform',
            name='GaseEm_approved_by1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gaseousemissionform',
            name='GaseEm_reviewd_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='calib_by',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='checked',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='checked1',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='luxanalysisform',
            name='lux_analyzedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='luxanalysisform',
            name='lux_approvedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='luxanalysisform',
            name='lux_approvedby1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='luxanalysisform',
            name='lux_reviewedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='machineoilform',
            name='machine_analyzedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='machineoilform',
            name='machine_approvedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='machineoilform',
            name='machine_approvedby1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='machineoilform',
            name='machine_reviewedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='microbialanalysis',
            name='micro_analyzedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='microbialanalysis',
            name='micro_approvedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='microbialanalysis',
            name='micro_approvedby1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='microbialanalysis',
            name='micro_reviewedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='noiseanalysis',
            name='analyzedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noiseanalysis',
            name='approvedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noiseanalysis',
            name='approvedby1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noiseanalysis',
            name='reviewedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='packingpolybagform',
            name='pack_analyzed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='packingpolybagform',
            name='pack_approved_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='packingpolybagform',
            name='pack_approved_by1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='packingpolybagform',
            name='pack_reviewed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='auth_sign',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='sampling_by',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiculemissionform',
            name='vehEm_analyzedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiculemissionform',
            name='vehEm_approvedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiculemissionform',
            name='vehEm_approvedby1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiculemissionform',
            name='vehEm_reviewedby',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='verification',
            name='checked',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='verification',
            name='checked1',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='verification',
            name='verif_by',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viscousliquid',
            name='analyzedby',
            field=models.ImageField(max_length=350, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viscousliquid',
            name='approvedby',
            field=models.ImageField(max_length=350, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viscousliquid',
            name='approvedby1',
            field=models.ImageField(max_length=350, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='viscousliquid',
            name='reviewedby',
            field=models.ImageField(max_length=350, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='analyzedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='approvedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='approvedby1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewaterform2',
            name='reviewedby',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewatersludge',
            name='ww_analyzed_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewatersludge',
            name='ww_approved_by',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewatersludge',
            name='ww_approved_by1',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wastewatersludge',
            name='ww_reviewd_by',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
