# Generated by Django 4.1.1 on 2025-06-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0177_signatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='signatures',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/users/'),
        ),
        migrations.AddField(
            model_name='signatures',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.role'),
        ),
    ]
