# Generated by Django 4.1.1 on 2025-06-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0178_role_alter_signatures_signature_signatures_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatures',
            name='office',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
