# Generated by Django 4.1.1 on 2025-06-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0179_signatures_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_aa2', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_aa2', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_aa2', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_aa', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_aa', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_aa', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='calib_by_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calib', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='checked1_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calib_check1', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='checked_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calib_check', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_dw', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_dw', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_dw', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_gae', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_gae', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_gae', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='check1_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect_check1', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='check_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect_check', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='ispect_by_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_la', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_la', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_la', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_mo', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_mo', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_mo', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_mb', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_mb', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_mb', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_na', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_na', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_na', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_ppb', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_ppb', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_ppb', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='auth_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='sampling_by_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampling_by', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_vem', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_vem', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_vem', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='verification',
            name='check1_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif_check1', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='verification',
            name='check_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif_check', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='verification',
            name='verif_by_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_vl', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_vl', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_vl', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_ww2', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_ww2', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_ww2', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_ww', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_ww', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_ww', to='EnviTechAlApp.signatures'),
        ),
        migrations.AlterField(
            model_name='signatures',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signatures',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
