# Generated by Django 4.1.1 on 2025-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0181_drinkingwaterform_pdf_desc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
