# Generated by Django 4.1.1 on 2025-08-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0183_ambientair2_created_at_ambientairform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aa2_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aa_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_cert_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gae_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insp_cert_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='la_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mo_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mb_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='na_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vem_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verif_cert_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vl_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ww2_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ww_reports_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
