# Generated by Django 4.1.1 on 2025-08-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0184_ambientair2_created_by_ambientairform_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='calib_by',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='checked',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='checked1',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='conc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='disc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='test9',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
