# Generated by Django 4.1.1 on 2025-08-23 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0185_alter_inspection_calib_by_alter_inspection_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry_sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ambientair2',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ambientairform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drinkingwaterform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loggingsheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='microbialanalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='noiseanalysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sample_registration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehiculemissionform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='viscousliquid',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wastewaterform2',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='created_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='verification',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
    ]
