# Generated by Django 4.1.1 on 2025-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0186_industry_sector_remove_ambientair2_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambientair2',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='ambientairform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='calibration',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='drinkingwaterform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='gaseousemissionform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='loggingsheet',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='luxanalysisform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='machineoilform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='microbialanalysis',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='noiseanalysis',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='packingpolybagform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='sample_registration',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='vehiculemissionform',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='viscousliquid',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='wastewaterform2',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='wastewatersludge',
            name='industry',
        ),
        migrations.AddField(
            model_name='ambientair2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loggingsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sample_registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
