# Generated by Django 4.1.1 on 2025-08-23 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0187_remove_ambientair2_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientair2',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='ambientairform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='gaseousemissionform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='luxanalysisform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='machineoilform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='noiseanalysis',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='packingpolybagform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='vehiculemissionform',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='viscousliquid',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='wastewaterform2',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AddField(
            model_name='wastewatersludge',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
    ]
