# Generated by Django 4.1.1 on 2025-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0190_alter_sample_registration_other_param_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_11',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_12',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_13',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_14',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_15',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_16',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_17',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_18',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_19',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_20',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_21',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_22',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_23',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_24',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_25',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_26',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_27',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_28',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_29',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_30',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_31',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_32',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_33',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_34',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_35',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_36',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_37',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_38',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_39',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_40',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_41',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_42',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_43',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_44',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_45',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_46',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_47',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_48',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_49',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_50',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_51',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_52',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_53',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_54',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_55',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_56',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_57',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_58',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_59',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_60',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_61',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_62',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_63',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_64',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_65',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_66',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='other_param_9',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_11',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_12',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_13',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_14',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_15',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_16',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_17',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_18',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_19',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_20',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_21',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_22',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_23',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_24',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_25',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_26',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_27',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_28',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_29',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_30',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_31',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_32',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_33',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_34',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_35',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_36',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_37',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_38',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_39',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_40',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_41',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_42',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_43',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_44',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_45',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_46',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_47',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_48',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_49',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_50',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_51',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_52',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_53',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_54',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_55',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_56',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_57',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_58',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_59',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_6',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_60',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_61',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_62',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_63',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_7',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_8',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sample_registration',
            name='ww_other_param_9',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
