# Generated by Django 4.1.1 on 2025-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0191_alter_sample_registration_other_param_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_registration',
            name='ww_other_param_64',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
