# Generated by Django 4.1.1 on 2025-10-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0192_sample_registration_ww_other_param_64'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_5',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_6',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='microbialanalysis',
            name='unit_head',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
