# Generated by Django 4.1.1 on 2025-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0193_microbialanalysis_unit_1_microbialanalysis_unit_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbialanalysis',
            name='extra_field',
            field=models.TextField(default=[]),
        ),
    ]
