# Generated by Django 4.1.1 on 2025-10-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0195_noisemonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemonitoring',
            name='table_data',
            field=models.JSONField(default=list),
        ),
    ]
