# Generated by Django 4.1.1 on 2025-10-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0196_noisemonitoring_table_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemonitoring',
            name='graph_type',
            field=models.CharField(blank=True, choices=[('line', 'Line Graph'), ('column', 'Column Graph')], default='line', max_length=10, null=True),
        ),
    ]
