# Generated by Django 4.1.1 on 2025-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0197_noisemonitoring_graph_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemonitoring',
            name='test_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noisemonitoring',
            name='test_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
