# Generated by Django 4.1.1 on 2025-10-14 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0198_noisemonitoring_test_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisemonitoring',
            name='analyzedby',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='approvedby',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='approvedby1',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='city_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='customlegend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='doc1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='doc2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='doc3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='editNote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='extra_field',
            field=models.TextField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnviTechAlApp.industry_sector'),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_11',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='pdf_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='results',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='reviewedby',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='table_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='times',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='units',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
