# Generated by Django 4.1.1 on 2026-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0199_alter_noisemonitoring_analyzedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_16',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_17',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_18',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_19',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_20',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_21',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_22',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_23',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_25',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_26',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_27',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_28',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_29',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_30',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_31',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_32',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drinkingwaterform',
            name='method_9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='customlegend',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='editNote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_11',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_8',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noisemonitoring',
            name='legend_9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
