# Generated by Django 4.1.1 on 2026-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0200_drinkingwaterform_method_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_1',
            field=models.CharField(default='*APHA 4500 H', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_10',
            field=models.CharField(default='*APHA 4500 Cl', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_11',
            field=models.CharField(default='HACH 8029', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_12',
            field=models.CharField(default='*APHA 3111-D', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_13',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_14',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_15',
            field=models.CharField(default='HACH 8014', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_16',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_17',
            field=models.CharField(default='*APHA 3114-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_18',
            field=models.CharField(default='HACH 8015', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_19',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_2',
            field=models.CharField(default='*APHA 2540-C', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_20',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_21',
            field=models.CharField(default='*APHA 3114-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_22',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_23',
            field=models.CharField(default='**HACH 8027', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_24',
            field=models.CharField(default='*APHA 3112-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_25',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_26',
            field=models.CharField(default='*APHA 3111-B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_27',
            field=models.CharField(default='HACH 10069', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_28',
            field=models.CharField(default='ASTM-D-1783', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_29',
            field=models.CharField(default='USEPA 1604', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_3',
            field=models.CharField(default='ASTM D 1126', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_30',
            field=models.CharField(default='*APHA 922 B', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_31',
            field=models.CharField(default='USEPA 1604', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_32',
            field=models.CharField(default='USEPA-614.1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_4',
            field=models.CharField(default='HACH 8025', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_5',
            field=models.CharField(default='*APHA 2130', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_6',
            field=models.CharField(default='HACH 8507', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_7',
            field=models.CharField(default='HACH 8039', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_8',
            field=models.CharField(default='*APHA 2160', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drinkingwaterform',
            name='method_9',
            field=models.CharField(default='*APHA 2150', max_length=50, null=True),
        ),
    ]
