# Generated by Django 4.1.1 on 2026-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0201_alter_drinkingwaterform_method_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastewaterform2',
            name='structured_data',
            field=models.TextField(default=[]),
        ),
    ]
