# Generated by Django 4.1.1 on 2026-01-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0202_wastewaterform2_structured_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatures',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures'),
        ),
    ]
