# Generated by Django 4.1.1 on 2026-04-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0203_alter_signatures_signature'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ambientair2',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_5c5d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientair2',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__4cd8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientair2',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__b7aac1_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientair2',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_3cfbd4_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientair2',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_afd42f_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientairform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_be28ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientairform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__65e008_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientairform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__13dfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientairform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_7de9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ambientairform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_3a3215_idx'),
        ),
        migrations.AddIndex(
            model_name='drinkingwaterform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_5949d1_idx'),
        ),
        migrations.AddIndex(
            model_name='drinkingwaterform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__4d30e5_idx'),
        ),
        migrations.AddIndex(
            model_name='drinkingwaterform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__b47f21_idx'),
        ),
        migrations.AddIndex(
            model_name='drinkingwaterform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_5bed6b_idx'),
        ),
        migrations.AddIndex(
            model_name='drinkingwaterform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_e2f79e_idx'),
        ),
        migrations.AddIndex(
            model_name='gaseousemissionform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_4c0103_idx'),
        ),
        migrations.AddIndex(
            model_name='gaseousemissionform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__82f007_idx'),
        ),
        migrations.AddIndex(
            model_name='gaseousemissionform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__6866a4_idx'),
        ),
        migrations.AddIndex(
            model_name='gaseousemissionform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_e10ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='gaseousemissionform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_554c58_idx'),
        ),
        migrations.AddIndex(
            model_name='luxanalysisform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_30a8f9_idx'),
        ),
        migrations.AddIndex(
            model_name='luxanalysisform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__65fe57_idx'),
        ),
        migrations.AddIndex(
            model_name='luxanalysisform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__eef932_idx'),
        ),
        migrations.AddIndex(
            model_name='luxanalysisform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_44be90_idx'),
        ),
        migrations.AddIndex(
            model_name='luxanalysisform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_88ed9b_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoilform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_c49153_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoilform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__1e6edd_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoilform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__0aec81_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoilform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_2903b7_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoilform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_129264_idx'),
        ),
        migrations.AddIndex(
            model_name='microbialanalysis',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_c1b711_idx'),
        ),
        migrations.AddIndex(
            model_name='microbialanalysis',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__2c1486_idx'),
        ),
        migrations.AddIndex(
            model_name='microbialanalysis',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__45ecd1_idx'),
        ),
        migrations.AddIndex(
            model_name='microbialanalysis',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_c1454a_idx'),
        ),
        migrations.AddIndex(
            model_name='microbialanalysis',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_1e74a8_idx'),
        ),
        migrations.AddIndex(
            model_name='noiseanalysis',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_23ce3f_idx'),
        ),
        migrations.AddIndex(
            model_name='noiseanalysis',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__bdfad4_idx'),
        ),
        migrations.AddIndex(
            model_name='noiseanalysis',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__45aa2f_idx'),
        ),
        migrations.AddIndex(
            model_name='noiseanalysis',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_0c8afb_idx'),
        ),
        migrations.AddIndex(
            model_name='noiseanalysis',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_b32790_idx'),
        ),
        migrations.AddIndex(
            model_name='noisemonitoring',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_c6c58e_idx'),
        ),
        migrations.AddIndex(
            model_name='noisemonitoring',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__f24136_idx'),
        ),
        migrations.AddIndex(
            model_name='noisemonitoring',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__49b45e_idx'),
        ),
        migrations.AddIndex(
            model_name='noisemonitoring',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_810d90_idx'),
        ),
        migrations.AddIndex(
            model_name='noisemonitoring',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_ce792f_idx'),
        ),
        migrations.AddIndex(
            model_name='packingpolybagform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_5b373f_idx'),
        ),
        migrations.AddIndex(
            model_name='packingpolybagform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__23f8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='packingpolybagform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__2cfb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='packingpolybagform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_12b1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='packingpolybagform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_c57a63_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculemissionform',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_64582f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculemissionform',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__7e8500_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculemissionform',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__05ea2c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculemissionform',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_a08be8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculemissionform',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_ba22d3_idx'),
        ),
        migrations.AddIndex(
            model_name='viscousliquid',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_c6694d_idx'),
        ),
        migrations.AddIndex(
            model_name='viscousliquid',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__f16b41_idx'),
        ),
        migrations.AddIndex(
            model_name='viscousliquid',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__2a432d_idx'),
        ),
        migrations.AddIndex(
            model_name='viscousliquid',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_a3503e_idx'),
        ),
        migrations.AddIndex(
            model_name='viscousliquid',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_22ab02_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewaterform2',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_4d4c49_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewaterform2',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__e7ca1d_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewaterform2',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__8f7e06_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewaterform2',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_8b2565_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewaterform2',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_3d13f2_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewatersludge',
            index=models.Index(fields=['reporting_date'], name='EnviTechAlA_reporti_206af4_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewatersludge',
            index=models.Index(fields=['report_to'], name='EnviTechAlA_report__b18ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewatersludge',
            index=models.Index(fields=['sample_id'], name='EnviTechAlA_sample__9203e1_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewatersludge',
            index=models.Index(fields=['city_location'], name='EnviTechAlA_city_lo_3aa410_idx'),
        ),
        migrations.AddIndex(
            model_name='wastewatersludge',
            index=models.Index(fields=['lab_report_no'], name='EnviTechAlA_lab_rep_f40e96_idx'),
        ),
    ]
