# Generated by Django 4.1.1 on 2026-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0205_clientdetails_jobcompletionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcompletionform',
            name='representative_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobcompletionform',
            name='representative_sign',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcompletionform',
            name='service_receiver',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
