# Generated by Django 4.1.1 on 2026-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0206_jobcompletionform_representative_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcompletionform',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
