# Generated by Django 4.1.1 on 2026-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0207_jobcompletionform_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcompletionform',
            name='job_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
