# Generated by Django 4.1.1 on 2026-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0208_jobcompletionform_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcompletionform',
            name='job_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
