# Generated by Django 4.1.1 on 2026-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0209_alter_jobcompletionform_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcompletionform',
            name='custom_po_fields',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='jobcompletionform',
            name='job_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
