# Generated by Django 4.1.1 on 2026-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0210_jobcompletionform_custom_po_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='po_reference',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='jobcompletionform',
            name='po_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
