# Generated by Django 4.1.1 on 2026-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0211_clientdetails_po_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='custom_po_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='po_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobcompletionform',
            name='po_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
