# Generated by Django 4.1.1 on 2026-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0212_clientdetails_custom_po_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='actual_read_head_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='actual_read_head_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='after_head_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='after_head_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='before_head_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='before_head_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='deviation_head_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='deviation_head_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='master_read_head_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='master_read_head_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='set_val_head_1',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='calibration',
            name='set_val_head_2',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
