from django.db import models
from EnviTechAlApp.models import *
# Create your models here.
class Detox(models.Model):
    analyst_signature = models.ForeignKey(Signatures, on_delete=models.SET_NULL, null=True, related_name='analyst_reports_detox')
    assistant_manager_signature = models.ForeignKey(Signatures, on_delete=models.SET_NULL, null=True, related_name='assistant_reports_detox')
    lab_manager_signature = models.ForeignKey(Signatures, on_delete=models.SET_NULL, null=True, related_name='lab_manager_reports_detox')
    location = models.CharField(max_length=100,blank=True,null=True)
    city_location = models.CharField(max_length=100,blank=True,null=True)
    lab_report_no = models.CharField(max_length=100,blank=True,null=True)
    invoice_bill_no = models.CharField(max_length=100,blank=True,null=True)
    reporting_date = models.CharField(max_length=100,blank=True,null=True)
    report_1 = models.CharField(max_length=100,blank=True,null=True)
    report_2 = models.CharField(max_length=100,blank=True,null=True)
    attention_1 = models.CharField(max_length=100,blank=True,null=True)
    attention_2 = models.CharField(max_length=100,blank=True,null=True)
    sample_id_1 = models.CharField(max_length=100,blank=True,null=True)
    sample_id_2 = models.CharField(max_length=100,blank=True,null=True)
    sample_col_date = models.CharField(max_length=100,blank=True,null=True)
    sample_des_1 = models.CharField(max_length=100,blank=True,null=True)
    sample_des_2 = models.CharField(max_length=100,blank=True,null=True)
    sample_method_1 = models.CharField(max_length=100,blank=True,null=True)
    sample_method_2 = models.CharField(max_length=100,blank=True,null=True)
    sample_type_1 = models.CharField(max_length=100,blank=True,null=True)
    sample_type_2 = models.CharField(max_length=100,blank=True,null=True)
    sample_tech_1 = models.CharField(max_length=100,blank=True,null=True)
    sample_tech_2 = models.CharField(max_length=100,blank=True,null=True)
    sample_col_by = models.CharField(max_length=100,blank=True,null=True)
    date_analysis = models.CharField(max_length=100,blank=True,null=True)
    date_analysis_to = models.CharField(max_length=100,blank=True,null=True)
    test_desc = models.CharField(max_length=100,blank=True,null=True)
    raw_water_1 = models.CharField(max_length=100,blank=True,null=True)
    wastewater_1 = models.CharField(max_length=100,blank=True,null=True)
    sludge_1 = models.CharField(max_length=100,blank=True,null=True)
    raw_water_2 = models.CharField(max_length=100,blank=True,null=True)
    wastewater_2 = models.CharField(max_length=100,blank=True,null=True)
    sludge_2 = models.CharField(max_length=100,blank=True,null=True)
    raw_water_3 = models.CharField(max_length=100,blank=True,null=True)
    wastewater_3 = models.CharField(max_length=100,blank=True,null=True)
    sludge_3 = models.CharField(max_length=100,blank=True,null=True)
    inlet = models.JSONField(default=dict)  
    outlet = models.JSONField(default=dict)  
    test = models.JSONField(default=dict)   
    extra_field = models.JSONField(default=dict)    
    extra_field_2 = models.JSONField(default=dict)   
    extra_field_3 = models.JSONField(default=dict)   
    extra_field_3_1 = models.JSONField(default=dict)   
    extra_field_4 = models.JSONField(default=dict)   
    extra_field_4_1 = models.JSONField(default=dict)   
    extra_field_5 = models.JSONField(default=dict)   
    extra_field_6 = models.JSONField(default=dict)   
    extra_field_7 = models.JSONField(default=dict)   
    extra_field_8 = models.JSONField(default=dict)   
    extra_field_8_1 = models.JSONField(default=dict)   
    extra_field_9 = models.JSONField(default=dict)   
    extra_field_10 = models.JSONField(default=dict)   
    extra_field_11 = models.JSONField(default=dict)   
    extra_field_12 = models.JSONField(default=dict)   
    extra_field_13 = models.JSONField(default=dict)   
    extra_field_14 = models.JSONField(default=dict)   
    extra_field_15 = models.JSONField(default=dict)   
    extra_field_16 = models.JSONField(default=dict)   
    extra_field_17 = models.JSONField(default=dict)  
    legend_1=models.CharField(max_length=100,blank=True,null=True)
    legend_2=models.CharField(max_length=100,blank=True,null=True)
    legend_3=models.CharField(max_length=100,blank=True,null=True)
    legend_4=models.CharField(max_length=100,blank=True,null=True)
    legend_5=models.CharField(max_length=100,blank=True,null=True)
    legend_6=models.CharField(max_length=100,blank=True,null=True)
    legend_7=models.CharField(max_length=100,blank=True,null=True)
    legend_8=models.CharField(max_length=100,blank=True,null=True)
    legend_9=models.CharField(max_length=100,blank=True,null=True)
    legend_10=models.CharField(max_length=100,blank=True,null=True)
    legend_11=models.CharField(max_length=100,blank=True,null=True)
    legend_12=models.CharField(max_length=100,blank=True,null=True)
    edit_note=models.CharField(max_length=100,blank=True,null=True)
    doc_1=models.CharField(max_length=100,blank=True,null=True)
    doc_2=models.CharField(max_length=100,blank=True,null=True)
    doc_3=models.CharField(max_length=100,blank=True,null=True)
    pdf_heading = models.CharField(max_length=200,null=True)
    pdf_image_1 = models.TextField(null=True,blank=True)  # base64 string
    pdf_desc_1 = models.TextField(null=True,blank=True)
    pdf_image_2 = models.TextField(null=True,blank=True)  # base64 string
    pdf_desc_2 = models.TextField(null=True,blank=True)
    pdf_image_3 = models.TextField(null=True,blank=True)  # base64 string
    pdf_desc_3 = models.TextField(null=True,blank=True)
    pdf_image_4 = models.TextField(null=True,blank=True)  # base64 string
    pdf_desc_4 = models.TextField(null=True,blank=True)
    pdf_image_5 = models.TextField(null=True,blank=True)  # base64 string
    pdf_desc_5 = models.TextField(null=True,blank=True)
    pdf_image_6 = models.TextField(null=True,blank=True)  # base64 string
    pdf_desc_6 = models.TextField(null=True,blank=True)
     
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.lab_report_no} - {self.reporting_date}"