# Generated by Django 4.1.1 on 2025-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dw_rds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rds', models.JSONField(default=dict)),
            ],
        ),
    ]
