# Generated by Django 4.2.4 on 2026-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dw_rds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rds', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='QCAuditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_manual_dw', models.BooleanField(default=False)),
                ('use_manual_ww', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QC Audit Config',
            },
        ),
        migrations.CreateModel(
            name='TestingResultsOfDWSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=dict)),
                ('location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingResultsOfWWSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=dict)),
                ('location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ww_rds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rds', models.JSONField(default=dict)),
            ],
        ),
    ]
