# Generated by Django 4.1.1 on 2026-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ww_rds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('rds', models.JSONField(default=dict)),
            ],
        ),
    ]
