# Generated by Django 4.2.30 on 2026-10-07 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("QC", "0002_historicalww_rds_historicaltestingresultsofwwsamples_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("Karachi", "Karachi"), ("Lahore", "Lahore")],
                        default="Karachi",
                        max_length=20,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("CRM", "CRM (Certified Reference Material)"),
                            ("RM", "Reference Material"),
                            ("IC", "Intermediate Check"),
                            ("DUP", "Duplicate"),
                            ("SPK", "Spike / Recovery"),
                        ],
                        default="CRM",
                        max_length=10,
                    ),
                ),
                ("parameter", models.CharField(max_length=120)),
                ("level", models.CharField(blank=True, default="", max_length=60)),
                ("unit", models.CharField(blank=True, default="mg/l", max_length=30)),
                ("equipment", models.CharField(blank=True, default="", max_length=160)),
                (
                    "equipment_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("method", models.CharField(blank=True, default="", max_length=120)),
                (
                    "crm_detail",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("crm_value", models.CharField(blank=True, default="", max_length=40)),
                (
                    "crm_range_low",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "crm_range_high",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="CRM Results during Monthly CRM Exercise",
                        max_length=200,
                    ),
                ),
                ("decimals", models.IntegerField(default=3)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["location", "parameter", "level", "equipment_id"],
            },
        ),
        migrations.CreateModel(
            name="ControlChartBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("established_on", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("values", models.JSONField(default=list)),
                ("mean", models.FloatField(blank=True, null=True)),
                ("sd", models.FloatField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="QC.controlchart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("chart", "version")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalControlChartSignoff",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField()),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="QC.controlchart",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical control chart signoff",
                "verbose_name_plural": "historical control chart signoffs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalControlChartResult",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "In control"),
                            ("warning", "Warning (>2 SD)"),
                            ("ooc", "Out of control (>3 SD)"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("remark", models.TextField(blank=True, default="")),
                ("performed_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "baseline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="QC.controlchartbaseline",
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="QC.controlchart",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical control chart result",
                "verbose_name_plural": "historical control chart results",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalControlChartBaseline",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("established_on", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("values", models.JSONField(default=list)),
                ("mean", models.FloatField(blank=True, null=True)),
                ("sd", models.FloatField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="QC.controlchart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical control chart baseline",
                "verbose_name_plural": "historical control chart baselines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalControlChart",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("Karachi", "Karachi"), ("Lahore", "Lahore")],
                        default="Karachi",
                        max_length=20,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("CRM", "CRM (Certified Reference Material)"),
                            ("RM", "Reference Material"),
                            ("IC", "Intermediate Check"),
                            ("DUP", "Duplicate"),
                            ("SPK", "Spike / Recovery"),
                        ],
                        default="CRM",
                        max_length=10,
                    ),
                ),
                ("parameter", models.CharField(max_length=120)),
                ("level", models.CharField(blank=True, default="", max_length=60)),
                ("unit", models.CharField(blank=True, default="mg/l", max_length=30)),
                ("equipment", models.CharField(blank=True, default="", max_length=160)),
                (
                    "equipment_id",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("method", models.CharField(blank=True, default="", max_length=120)),
                (
                    "crm_detail",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("crm_value", models.CharField(blank=True, default="", max_length=40)),
                (
                    "crm_range_low",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "crm_range_high",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="CRM Results during Monthly CRM Exercise",
                        max_length=200,
                    ),
                ),
                ("decimals", models.IntegerField(default=3)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical control chart",
                "verbose_name_plural": "historical control charts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ControlChartResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "In control"),
                            ("warning", "Warning (>2 SD)"),
                            ("ooc", "Out of control (>3 SD)"),
                        ],
                        default="ok",
                        max_length=10,
                    ),
                ),
                ("remark", models.TextField(blank=True, default="")),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "baseline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="QC.controlchartbaseline",
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="QC.controlchart",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ControlChartSignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signoffs",
                        to="QC.controlchart",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("chart", "year")},
            },
        ),
    ]
