# Generated by Django 4.1.1 on 2026-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_ww_rds'),
    ]

    operations = [
        migrations.AddField(
            model_name='dw_rds',
            name='audit_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ww_rds',
            name='audit_url',
            field=models.BooleanField(default=False),
        ),
    ]
