# Generated by Django 4.1.1 on 2026-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0003_dw_rds_audit_url_ww_rds_audit_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCAuditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_manual_dw', models.BooleanField(default=False)),
                ('use_manual_ww', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dw_rds',
            name='audit_url',
        ),
        migrations.RemoveField(
            model_name='ww_rds',
            name='audit_url',
        ),
    ]
