# Generated by Django 4.2.30 on 2026-10-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QC", "0004_control_chart_reviewer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="controlchartsignoff",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="controlchartsignoff",
            name="month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcontrolchartsignoff",
            name="month",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="controlchartsignoff",
            unique_together={("chart", "year", "month")},
        ),
    ]
