# Generated by Django 4.1.1 on 2026-04-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0004_qcauditconfig_remove_dw_rds_audit_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcauditconfig',
            options={'verbose_name': 'QC Audit Config'},
        ),
    ]
