# Generated by Django 4.2.30 on 2026-10-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QC", "0005_signoff_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlchart",
            name="start_month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicalcontrolchart",
            name="start_month",
            field=models.IntegerField(default=1),
        ),
    ]
