# Generated by Django 4.1.1 on 2026-04-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0005_alter_qcauditconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingResultsOfDWSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TestingResultsOfWWSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=dict)),
            ],
        ),
    ]
