# Generated by Django 4.1.1 on 2026-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0006_testingresultsofdwsamples_testingresultsofwwsamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingresultsofdwsamples',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='testingresultsofwwsamples',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
