# Generated by Django 4.2.30 on 2026-10-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QC", "0006_chart_start_month"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlchartresult",
            options={"ordering": ["date", "time", "id"]},
        ),
        migrations.AddField(
            model_name="controlchartresult",
            name="time",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="historicalcontrolchartresult",
            name="time",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="controlchart",
            name="activity",
            field=models.CharField(
                choices=[
                    ("CRM", "CRM (Certified Reference Material)"),
                    ("RM", "Reference Material"),
                    ("IC", "Intermediate Check"),
                    ("DUP", "Duplicate"),
                    ("SPK", "Spike / Recovery"),
                    ("MON", "Monitoring (temperature / humidity)"),
                ],
                default="CRM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolchart",
            name="activity",
            field=models.CharField(
                choices=[
                    ("CRM", "CRM (Certified Reference Material)"),
                    ("RM", "Reference Material"),
                    ("IC", "Intermediate Check"),
                    ("DUP", "Duplicate"),
                    ("SPK", "Spike / Recovery"),
                    ("MON", "Monitoring (temperature / humidity)"),
                ],
                default="CRM",
                max_length=10,
            ),
        ),
    ]
