# Generated by Django 4.2.30 on 2026-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QC", "0007_monitoring_reading_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlchart",
            name="doc_no",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="controlchart",
            name="limit_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed acceptance limits"),
                    ("baseline", "Baseline (+/- 2/3 SD), e.g. seasonal"),
                    ("run", "The month's own readings (+/- 2/3 SD)"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="controlchartresult",
            name="reading_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controlchartresult",
            name="reading_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontrolchart",
            name="doc_no",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="historicalcontrolchart",
            name="limit_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed acceptance limits"),
                    ("baseline", "Baseline (+/- 2/3 SD), e.g. seasonal"),
                    ("run", "The month's own readings (+/- 2/3 SD)"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrolchartresult",
            name="reading_1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontrolchartresult",
            name="reading_2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
