# Generated by Django 4.2.30 on 2026-07-16 19:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnviTechAlApp', '0011_alter_ambientair2_analyzedby_and_more'),
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecipeLabour',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('minutes_sample', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Minutes / sample')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('grade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costing.labourgrade')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costing.costparameter')),
            ],
            options={
                'verbose_name': 'historical Recipe — labour',
                'verbose_name_plural': 'historical Recipe — labour',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecipeChemical',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('qty_sample', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Qty / sample')),
                ('qty_batch', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Qty / batch')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chemical', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EnviTechAlApp.chemicalitem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parameter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costing.costparameter')),
            ],
            options={
                'verbose_name': 'historical Recipe — chemical',
                'verbose_name_plural': 'historical Recipe — chemicals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReagentRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', help_text='Blank = applies to all labs; else Karachi / Lahore', max_length=32)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Unit cost (PKR / base unit)')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='e.g. Stock valuation 31-07-2026 / PO ref', max_length=128)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chemical', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='EnviTechAlApp.chemicalitem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Reagent rate',
                'verbose_name_plural': 'historical Reagent rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLabourGrade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('office', models.CharField(blank=True, max_length=32)),
                ('gross_month', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gross salary / month (PKR)')),
                ('is_direct', models.BooleanField(default=True, verbose_name='Direct (chargeable) staff')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical labour grade',
                'verbose_name_plural': 'historical labour grades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCostParameter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('matrix', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(default='Karachi', max_length=32)),
                ('batch_size', models.PositiveIntegerField(default=10)),
                ('annual_volume', models.PositiveIntegerField(default=1000)),
                ('electricity_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Electricity kWh / sample')),
                ('di_water_ml', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DI water mL / sample')),
                ('instrument_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Instrument PKR / sample')),
                ('waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Waste PKR / sample')),
                ('qc_batch_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='QC & calibration PKR / batch')),
                ('annual_pool', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Accreditation/PT/LIMS PKR / year')),
                ('tax_category', models.CharField(default='SST - services', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cost parameter',
                'verbose_name_plural': 'historical cost parameters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCostingConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=64)),
                ('working_days', models.DecimalField(decimal_places=2, default=Decimal('22'), max_digits=6, verbose_name='Working days / month')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('7'), max_digits=6, verbose_name='Productive hours / day')),
                ('utilisation', models.DecimalField(decimal_places=3, default=Decimal('0.75'), max_digits=5, verbose_name='Chargeable utilisation')),
                ('employer_uplift', models.DecimalField(decimal_places=3, default=Decimal('0.12'), max_digits=5, verbose_name='Employer uplift on gross')),
                ('electricity_tariff', models.DecimalField(decimal_places=4, default=Decimal('39.80'), max_digits=10, verbose_name='Electricity (PKR/kWh)')),
                ('di_water_cost', models.DecimalField(decimal_places=4, default=Decimal('0.50'), max_digits=10, verbose_name='DI water (PKR/mL)')),
                ('rework_factor', models.DecimalField(decimal_places=3, default=Decimal('0.05'), max_digits=5, verbose_name='Repeat-rework factor')),
                ('lab_overhead', models.DecimalField(decimal_places=3, default=Decimal('0.18'), max_digits=5, verbose_name='Lab overhead')),
                ('ga_overhead', models.DecimalField(decimal_places=3, default=Decimal('0.07'), max_digits=5, verbose_name='G&A overhead')),
                ('target_margin', models.DecimalField(decimal_places=3, default=Decimal('0.30'), max_digits=5, verbose_name='Target margin (markup)')),
                ('price_rounding', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=8, verbose_name='Price rounding (PKR)')),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Costing configuration',
                'verbose_name_plural': 'historical Costing configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
