# Generated by Django 4.2.30 on 2026-07-17 13:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_historicalrecipelabour_historicalrecipechemical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingconfig',
            name='thin_margin_pct',
            field=models.DecimalField(decimal_places=1, default=Decimal('15'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Thin-margin flag threshold (%)'),
        ),
        migrations.AddField(
            model_name='historicalcostingconfig',
            name='thin_margin_pct',
            field=models.DecimalField(decimal_places=1, default=Decimal('15'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Thin-margin flag threshold (%)'),
        ),
        migrations.AlterField(
            model_name='costparameter',
            name='annual_pool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Accreditation/PT/LIMS PKR / year'),
        ),
        migrations.AlterField(
            model_name='costparameter',
            name='di_water_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='DI water mL / sample'),
        ),
        migrations.AlterField(
            model_name='costparameter',
            name='electricity_kwh',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Electricity kWh / sample'),
        ),
        migrations.AlterField(
            model_name='costparameter',
            name='instrument_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Instrument PKR / sample'),
        ),
        migrations.AlterField(
            model_name='costparameter',
            name='qc_batch_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='QC & calibration PKR / batch'),
        ),
        migrations.AlterField(
            model_name='costparameter',
            name='waste_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Waste PKR / sample'),
        ),
        migrations.AlterField(
            model_name='historicalcostparameter',
            name='annual_pool',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Accreditation/PT/LIMS PKR / year'),
        ),
        migrations.AlterField(
            model_name='historicalcostparameter',
            name='di_water_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='DI water mL / sample'),
        ),
        migrations.AlterField(
            model_name='historicalcostparameter',
            name='electricity_kwh',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Electricity kWh / sample'),
        ),
        migrations.AlterField(
            model_name='historicalcostparameter',
            name='instrument_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Instrument PKR / sample'),
        ),
        migrations.AlterField(
            model_name='historicalcostparameter',
            name='qc_batch_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='QC & calibration PKR / batch'),
        ),
        migrations.AlterField(
            model_name='historicalcostparameter',
            name='waste_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Waste PKR / sample'),
        ),
        migrations.AlterField(
            model_name='historicallabourgrade',
            name='gross_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gross salary / month (PKR)'),
        ),
        migrations.AlterField(
            model_name='historicalreagentrate',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit cost (PKR / base unit)'),
        ),
        migrations.AlterField(
            model_name='historicalrecipechemical',
            name='qty_batch',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qty / batch'),
        ),
        migrations.AlterField(
            model_name='historicalrecipechemical',
            name='qty_sample',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qty / sample'),
        ),
        migrations.AlterField(
            model_name='historicalrecipelabour',
            name='minutes_sample',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minutes / sample'),
        ),
        migrations.AlterField(
            model_name='labourgrade',
            name='gross_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gross salary / month (PKR)'),
        ),
        migrations.AlterField(
            model_name='reagentrate',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Unit cost (PKR / base unit)'),
        ),
        migrations.AlterField(
            model_name='recipechemical',
            name='qty_batch',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qty / batch'),
        ),
        migrations.AlterField(
            model_name='recipechemical',
            name='qty_sample',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qty / sample'),
        ),
        migrations.AlterField(
            model_name='recipelabour',
            name='minutes_sample',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minutes / sample'),
        ),
        migrations.AddConstraint(
            model_name='reagentrate',
            constraint=models.UniqueConstraint(fields=('chemical', 'location'), name='uniq_rate_chemical_location'),
        ),
    ]
