"""
URL configuration for EnviTechAlApp project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django import views
from django.contrib import admin
from django.urls import include, path,re_path
from EnviTechAlApp import settings, views
from django.conf.urls.static import static
# from django.conf.urls import url, include
from django.views.static import serve 

handler500 = 'EnviTechAlApp.views.custom_500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('detox/', include('detox.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('qc/', include('QC.urls')),
    path('login/',views.userlogin,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('home/', views.home, name="home"),
    path('', views.nav, name = "nav"),
    path('certificate/', views.certificate, name = "certificate"),
    path('calibration/', views.calibration, name = "calibration"),
    path('calibration_view/<str:pk>/',views.calib_view,name='calib_view'),
    path('calibration_delete/<str:pk>/',views.calib_delete,name='calibration_delete'),
    path('calibration_list',views.calib_list,name='calib_list'),
    path('calibration_edit/<str:pk>/',views.calib_edit,name='calib_edit'),
    path('calibration_update/<str:pk>/',views.calib_update,name='calib_update'),
    path('calibration_clone_update/<str:pk>/',views.calib_clone_update,name='calib_clone_update'),
    path('calibration_clone/<str:pk>/',views.calib_clone,name='calib_clone'),
    path('calibration_pdf/<str:pk>/',views.calib_pdf,name='calib_pdf'),
    path('calibration_pdf1/<str:pk>/',views.calib_pdf1,name='calib_pdf1'),
    path('inspection/', views.inspection, name = "inspection"),
    path('inspection_list/', views.inspection_list, name = "inspection_list"),
    path('inspection_edit/<str:pk>/',views.inspect_edit,name='inspect_edit'),
    path('inspection_update/<str:pk>/',views.inspect_update,name='inspect_update'),
    path('inspect_delete/<str:pk>/',views.inspect_delete,name='inspect_delete'),
    path('inspection_clone_update/<str:pk>/',views.inspect_clone_update,name='inspect_clone_update'),
    path('inspection_clone/<str:pk>/',views.inspect_clone,name='inspect_clone'),
    path('inspection_view/<str:pk>/',views.inspect_view,name='inspect_view'),
    path('inspection_pdf/<str:pk>/',views.inspect_pdf,name='inspect_pdf'),
    path('inspection_pdf1/<str:pk>/',views.inspect_pdf1,name='inspect_pdf1'),
    path('verification/', views.verification, name = "verification"),
    path('verification_list/', views.verification_list, name = "verification_list"),
    path('verification_edit/<str:pk>/',views.verif_edit,name='verif_edit'),
    path('verification_update/<str:pk>/',views.verif_update,name='verif_update'),
    path('verif_delete/<str:pk>/',views.verif_delete,name='verif_delete'),
    path('verification_clone_update/<str:pk>/',views.verif_clone_update,name='verif_clone_update'),
    path('verification_clone/<str:pk>/',views.verif_clone,name='verif_clone'),
    path('verification_view/<str:pk>/',views.verif_view,name='verif_view'),
    path('verification_pdf/<str:pk>/',views.verif_pdf,name='verif_pdf'),
    path('verification_pdf1/<str:pk>/',views.verif_pdf1,name='verif_pdf1'),
    path('drinkingWaterForm', views.drinkingWaterForm),
    path('gaseousEmission',views.gaseousEmission),
    path('ambientAir',views.ambientAirForm),
    path('wasteWaterSludge',views.wasteWaterSludge,name="wasteWaterSludge"),
    path('vehicularEmission',views.vehicularEmission,name="vahicularEmission"),
    path('luxAnalysis',views.luxAnalysis,name="luxAnalysis"),
    path('noiseAnalysis',views.noiseAnalysis,name="noiseAnalysis"),
    path('packingPolyBag',views.packingPoly,name="packingPolyBag"),
    path('machineOil',views.machineOil,name="machineOil"),
    path('microbialAnalysis',views.microbialAnalysis,name="microBialAnalysis"),
    path('viscousLiquid',views.viscousLiquid,name="viscousLiquid"),
    path('ambientAirQuality2',views.ambientAirQuality2,name="ambientAir2"),
    path('wasteWater2',views.wasteWater2,name="wasteWater2"),
    path('drinkingWaterList',views.drinkingWaterList,name="drinkWaterList"),
    path('delete-form/<str:pk>/',views.deleteDrinkingWaterList,name='DriningWaterform-delete'),
    path('edit-form/<str:pk>/',views.editDrinkingWaterList,name='DrinkingWaterform-edit'),
    path('updateRecord<str:pk>/',views.editDrinkingWaterListRecord,name='DrinkingWaterform-editRecord'),
    path('view-form/<str:pk>/',views.drinkWaterReport,name='DrinkingWaterform-view'),
    path('drinkingwaterReport-pdf/<int:pk>/',views.generatePDF,name="drinkingwaterReport-pdf"),
    path('drinkingwaterReport-pdf1/<int:pk>/',views.generatePDF_report,name="drinkingwaterReport-pdf1"),
    path('DriningWaterform-clone/<str:pk>/',views.drinkingWaterClone,name="DriningWaterform-clone"),
    path('DriningWaterform-Save/<str:pk>/',views.drinkingWaterCloneSave,name="DriningWaterform-Save"),
    path('gaseousEmissionList',views.gaseousEmissionList,name="gaseousEmissionList"),
    path('GaseousForm-delete/<str:pk>/',views.deleteGaseousList,name='GaseousForm-delete'),
    path('GaseousForm-edit/<str:pk>/',views.editGaseousList,name='GaseousForm-edit'),
    path('GaseousForm-updateRecord<str:pk>/',views.updateGaseousRecord,name='GaseousForm-editRecord'),
    path('GaseousForm-view-form/<str:pk>/',views.gaseousEmissionReport,name='GaseousForm-view'),
    path('GaseousForm-clone/<str:pk>/',views.GaseousFormclone,name="GaseousForm-clone"),
    path('GaseousForm-Save/<str:pk>/',views.GaseousFormcloneSave,name="GaseousForm-Save"),
    path('gaseousEmissionReport-pdfPrint/<int:pk>/',views.gaseousReportgeneratePDF,name="gaseousEmissionReport-pdfPrint"),
    path('gaseousEmissionReport-pdfReport/<int:pk>/',views.gaseousReportgeneratePDF1,name="gaseousEmissionReport-pdfReport"),
    path('ambientAirList',views.ambientAirList,name="ambientAirList"),
    path('ambientAir-delete/<str:pk>/',views.ambientAirDelete,name="ambientAir-delete"),
    path('ambientAir-edit/<str:pk>/',views.ambientAirEdit,name="ambientAir-edit"),
    path('ambientAir-updateRecord/<str:pk>/',views.ambientAirUpdateRecord,name="ambientAir-editRecord"),
    path('ambientAir-view/<str:pk>/',views.ambientAirview,name="ambientAir-view"),
    path('ambientAir-clone/<str:pk>/',views.ambientAirClone,name="ambientAir-clone"),
    path('ambientAir-Save/<str:pk>/',views.ambientAircloneSave,name="ambientAir-Save"),
    path('ambientAirReport-pdfPrint/<int:pk>/',views.ambientAirGeneratePDF,name="AmbientAirReport-pdfPrint"),
    path('ambientAirReport-pdfReport/<int:pk>/',views.ambientAirGeneratePDF1,name="AmbientAirReport-pdfReport"),
    path('wasteWaterSludgeList/',views.wasteWaterSludgeList,name="wasteWaterSludgeList"),
    path('wasteWaterSludge-delete/<str:pk>/',views.wasteWaterSludgeDelete,name="wastewater-delete"),
    path('wasteWaterSludge-edit/<str:pk>/',views.wastewaterEdit,name="wastewater-edit"),
    path('wasteWaterSludge-update/<str:pk>/',views.wasteWaterUpdate,name="wastewater-update"),
    path('wasteWaterSludge-view/<str:pk>/',views.wasteWaterView,name="wastewater-view"),
    path('wastewater-clone/<str:pk>/',views.wasteWaterclone,name="wastewater-clone"),
    path('wasteWater-Save/<str:pk>/',views.wasteWatercloneSave,name="wasteWater-Save"),
    path('wasteWaterSludgeReport-pdfPrint1/<str:pk>/',views.wasteWaterPdf0,name="wastewaterReport-pdfPrint1"),
    path('wasteWaterSludgeReport-pdfReport1/<str:pk>/',views.wasteWaterPdf1,name="wastewaterReport-pdfReport1"),
    path('vehicularEmissionList/',views.vehicularEmissionList,name="vehicularEmissionList"),
    path('vehicularEmission-delete/<str:pk>/',views.vehicularEmissionDelete,name="vehicularEmission-delete"),
    path('vehicularEmission-edit/<str:pk>/',views.vehicularEmissionEdit,name="vehicularEmission-edit"),
    path('vehicularEmission-Update/<str:pk>/',views.vehicularEmissionUpdate,name="vehicularEmission-update"),
    path('vehicularEmission-view/<str:pk>/',views.vehicularEmissionView,name="vehicularEmission-view"),
    path('vehicularEmission-clone/<str:pk>/',views.vehicularEmissionclone,name="vehicularEmission-clone"),
    path('vehicularEmission-Save/<str:pk>/',views.vehicularEmissioncloneSave,name="vehicularEmission-Save"),
    path('vehicularEmissionReport-pdfPrint/<str:pk>/',views.vehicularEmissionReport,name="vehicularEmissionReport-pdfPrint"),
    path('vehicularEmissionReport-pdfReport/<str:pk>/',views.vehicularEmissionReport1,name="vehicularEmissionReport-pdfReport"),
    path('luxAnalysisList/',views.luxAnalysisList,name="luxAnalysisList"),
    path('luxAnalysis-delete/<str:pk>/',views.luxAnalysisDelete,name="luxAnalysis-delete"),
    path('luxAnalysis-edit/<str:pk>/',views.luxAnalysisEdit,name="luxAnalysis-edit"),
    path('luxAnalysis-update/<str:pk>/',views.luxAnalysisUpdate,name="luxAnalysis-update"),
    path('luxAnalysisReport/<str:pk>/',views.luxAnalysisView,name="luxAnalysis-view"),
    path('luxAnalysis-clone/<str:pk>/',views.luxFormclone,name="luxAnalysis-clone"),
    path('luxForm-Save/<str:pk>/',views.luxFormcloneSave,name="luxForm-Save"),
    path('luxAnalysisReport-pdfPrint/<str:pk>/',views.luxAnalysisReportPdf,name="luxAnalysisReport-pdfPrint"),
    path('luxAnalysisReport-pdfReport/<str:pk>/',views.luxAnalysisReportPdf1,name="luxAnalysisReport-pdfReport"),
    path('packingPolyBagList/',views.packingPolyBagList,name="packingPolyBagList"),
    path('packingpolybag-delete/<str:pk>/',views.packingPolyBagDelete,name="packingpolybag-delete"),
    path('packingpolybag-edit/<str:pk>/',views.packingPolyBagEdit,name="packingpolybag-edit"),
    path('packingpolybag-Update/<str:pk>/',views.packingPolyBagUpdate,name="packingpolybag-update"),
    path('packingpolybag-view/<str:pk>/',views.packingPolyBagView,name="packingpolybag-view"),
    path('packingpolybag-clone/<str:pk>/',views.packingPolyclone,name="packingpolybag-clone"),
    path('packingPoly-Save/<str:pk>/',views.packingPolycloneSave,name="packingPoly-Save"),
    path('packingpolybagReport-pdfPrint/<str:pk>/',views.packingPolyBagReport,name="packingpolybagReport-pdfPrint"),
    path('packingpolybagReport-pdfReport/<str:pk>/',views.packingPolyBagReport1,name="packingpolybagReport-pdfReport"),
    path('noiseAnalysisList/',views.noiseAnalysisList,name="noiseAnalysisList"),
    path('noiseAnalysis-delete<str:pk>/',views.noiseAnalysisDelete,name="noiseAnalysis-delete"),
    path('noiseAnalysis-edit<str:pk>/',views.noiseAnalysisEdit,name="noiseAnalysis-edit"),
    path('noiseAnalysis-update<str:pk>/',views.noiseAnalysisUpdate,name="noiseAnalysis-update"),
    path('noiseAnalysis-view/<str:pk>/',views.noiseAnalysisView,name="noiseAnalysis-view"),
    path('noiseAnalysis-clone/<str:pk>/',views.noiseAnalysisclone,name="noiseAnalysis-clone"),
    path('noiseAnalysis-Save/<str:pk>/',views.noiseAnalysiscloneSave,name="noiseAnalysis-Save"),
    path('noiseAnalysisReport-pdfPrint/<str:pk>/',views.noiseAnalysisReport,name="noiseAnalysisReport-pdfPrint"),
    path('noiseAnalysisReport-pdfReport/<str:pk>/',views.noiseAnalysisReport1,name="noiseAnalysisReport-pdfReport"),
    path('machineOilList/',views.machineOilList,name="machineOilList"),
    path('machineOil-delete/<str:pk>/',views.machineOilDelete,name="machineOil-delete"),
    path('machineOil-edit/<str:pk>/',views.machineOilEdit,name="machineOil-edit"),
    path('machineOil-update/<str:pk>/',views.machineOilUpdate,name="machineOil-update"),
    path('machineOil-view/<str:pk>/',views.machineOilView,name="machineOil-view"),
    path('machineOil-clone/<str:pk>/',views.machineOilclone,name="machineOil-clone"),
    path('machineOil-Save/<str:pk>/',views.machineOilcloneSave,name="machineOil-Save"),
    path('machineOilReport-PdfPrint/<str:pk>/',views.machineOilReportPdf,name="machineOilReport-pdfPrint"),
    path('machineOilReport-PdfReport/<str:pk>/',views.machineOilReportPdf1,name="machineOilReport-pdfReport"),
    path('microbialList/',views.microbialList,name="microbialList"),
    path('microbial-delete/<str:pk>/',views.microbialDelete,name="microbial-delete"),
    path('microbial-edit/<str:pk>/',views.microbialEdit,name="microbial-edit"),
    path('microbial-update/<str:pk>/',views.microbialUpdate,name="microbial-update"),
    path('microbial-view/<str:pk>/',views.microbialView,name="microbial-view"),
    path('microbial-clone/<str:pk>/',views.microbialclone,name="microbial-clone"),
    path('microbial-Save/<str:pk>/',views.microbialcloneSave,name="microbial-Save"),
    path('microbialAnalysisReport-pdfPrint/<str:pk>/',views.microbialAnalysisPdf,name="microbialAnalysisReport-pdfPrint"),
    path('microbialAnalysisReport-pdfReport/<str:pk>/',views.microbialAnalysisPdf1,name="microbialAnalysisReport-pdfReport"),
    path('viscousLiquidList/',views.viscousLiquidList,name="viscousLiquidList"),
    path('viscousLiquid-delete/<str:pk>/',views.viscousLiquidDelete,name="viscousLiquid-delete"),
    path('viscousLiquid-edit/<str:pk>/',views.viscousLiquidEdit,name="viscousLiquid-edit"),
    path('viscousLiquid-update/<str:pk>/',views.viscousLiquidUpdate,name="viscousLiquid-update"),
    path('viscousLiquid-view/<str:pk>/',views.viscousLiquidview,name="viscousLiquid-view"),
    path('viscousLiquid-clone/<str:pk>/',views.viscousLiquidclone,name="viscousLiquid-clone"),
    path('viscousLiquid-Save/<str:pk>/',views.viscousLiquidcloneSave,name="viscousLiquid-Save"),
    path('viscousLiquid-PdfPrint/<str:pk>/',views.viscousLiquidPdf,name="viscousLiquid-PdfPrint"),
    path('viscousLiquid-PdfReport/<str:pk>/',views.viscousLiquidPdf1,name="viscousLiquid-PdfReport"),
    path('ambientAir2List/',views.ambientAir2List,name="ambientAir2List"),
    path('ambientAir2-delete/<str:pk>/',views.ambientAir2Delete,name="ambientAir2-delete"),
    path('ambientAir2-edit/<str:pk>/',views.ambientAir2Edit,name="ambientAir2-edit"),
    path('ambientAir2-update/<str:pk>/',views.ambientAir2Update,name="ambientAir2-update"),
    path('ambientAir2-view/<str:pk>/',views.ambientAir2View,name="ambientAir2-view"),
    path('ambientAir2-clone/<str:pk>/',views.ambientAir2Clone,name="ambientAir2-clone"),
    path('ambientAir2-Save/<str:pk>/',views.ambientAir2cloneSave,name="ambientAir2-Save"),
    path('ambientAir2Report-pdfPrint/<str:pk>/',views.ambientAir2Pdf,name="ambientAir2Report-pdfPrint"),
    path('ambientAir2Report-pdfReport/<str:pk>/',views.ambientAir2Pdf1,name="ambientAir2Report-pdfReport"),
    path('wasteWater2List/',views.wasteWAter2List,name="wasteWater2List"),
    path('wasteWater2-delete/<str:pk>/',views.wasteWAter2Delete,name="wasteWater2-delete"),
    path('wasteWater2-edit/<str:pk>/',views.wasteWAter2Edit,name="wasteWater2-edit"),
    path('wasteWater2-Update/<str:pk>/',views.wasteWAter2Update,name="wasteWater2-Update"),
    path('wasteWater2-view/<str:pk>/',views.wasteWAter2View,name="wasteWater2-view"),
    path('wasteWater2-clone/<str:pk>/',views.wasteWater2clone,name="wasteWater2-clone"),
    path('wasteWater2-Save/<str:pk>/',views.wasteWater2cloneSave,name="wasteWater2-Save"),
    path('wasteWater2Report-pdfPrint/<str:pk>/',views.wasteWater2Pdf,name="wasteWater2Report-pdfPrint"),
    path('wasteWater2Report-pdfReport/<str:pk>/',views.wasteWater2Pdf1,name="wasteWater2Report-pdfReport"),
    path('generate_merged_pdf/', views.generate_merged_pdf, name='generate_merged_pdf'),
    path('etal-bulk-pdf/', views.etal_bulk_pdf, name='etal_bulk_pdf'),
    path('etal-bulk-approve/', views.etal_bulk_approve, name='etal_bulk_approve'),
    path('etal-approval-state/', views.etal_approval_state, name='etal_approval_state'),
    path('generate_merged_cert/', views.generate_merged_pdf_certificate, name='generate_merged_cert'),
    path('sample_main/', views.sample_main, name="sample_main"),
    path('sample_reg/', views.sample_reg, name="sample_reg"),
    path('sample_list/', views.sample_list, name="sample_list"),
    path('sample_view/<str:pk>/', views.sample_view, name="sample_view"),
    path('sample_edit/<str:pk>/', views.sample_edit, name="sample_edit"),
    path('sample_update/<str:pk>/', views.sample_update, name="sample_update"),
    path('sample_clone/<str:pk>/', views.sample_clone, name="sample_clone"),
    path('sample_clone_update/<str:pk>/', views.sample_clone_update, name="sample_clone_update"),
    path('sample_delete/<str:pk>/', views.sample_delete, name="sample_delete"),
    path('sample-pdfPrint/<str:pk>/',views.samplePdf,name="sample-pdfPrint"),
    path('sample-pdfPrint1/<str:pk>/',views.samplePdf1,name="sample-pdfPrint1"),
    path('addLogging/',views.addLogging,name="addLogging"),
    path('loggingSheet/',views.loggingSheet,name="loggingSheet"),
    path('log-pdf/',views.logPdf,name="log-pdf"),
    path('loggingEdit/<str:pk>/', views.loggingEdit, name="loggingEdit"),
    path('loggingUpdate/<str:pk>/', views.loggingUpdate, name="loggingUpdate"),
    path('loggingClone/<str:pk>/', views.loggingClone, name="loggingClone"),
    path('loggingCloneUpdate/<str:pk>/', views.loggingCloneUpdate, name="loggingCloneUpdate"),
    path('loggingList/', views.loggingList, name="loggingList"),
    path('loggingDelete/<str:pk>/', views.loggingDelete, name="loggingDelete"),
    path('loggingView/<str:pk>/', views.loggingView, name="loggingView"),
    path('error/', views.custom_500, name="error"),
    path('noisemonitoring/', views.noisemonitoring, name="noisemonitoring"),
    path('noiseMonitoring_list/', views.noiseMonitoring_list, name="noiseMonitoring_list"),
    path('noiseMonitoring_view/<str:pk>/', views.noiseMonitoring_view, name="noiseMonitoring_view"),
    path('noiseMonitoring_print/<str:pk>/', views.noiseMonitoring_print, name="noiseMonitoring_print"),
    path('noiseMonitoring_report/<str:pk>/', views.noiseMonitoring_report, name="noiseMonitoring_report"),
    path('noiseMonitoring_edit/<str:pk>/', views.noiseMonitoring_edit, name="noiseMonitoring_edit"),
    path('noiseMonitoring_clone/<str:pk>/', views.noiseMonitoring_clone, name="noiseMonitoring_clone"),
    path('noiseMonitoring_clone_update/<str:pk>/', views.noiseMonitoring_clone_update, name="noiseMonitoring_clone_update"),
    path('noiseMonitoring_edit_update/<str:pk>/', views.noiseMonitoring_edit_update, name="noiseMonitoring_edit_update"),
    path('job_main', views.job_main, name="job_main"),
    path('job-completion-form', views.job_completion_form, name="job_completion_form"),
    path('api/save-client-details/', views.save_client_details, name='save_client_details'),
    path('api/get-client-details/', views.get_client_details, name='get_client_details'),
    path('api/get-all-companies/', views.get_all_companies, name='get_all_companies'),
    path('job_completion_edit/<str:pk>', views.job_completion_edit, name="job_completion_edit"),
    path('api/update_job/<int:pk>/', views.update_job_completion, name='update_job'),
    path('job_completion_clone/<int:pk>/', views.job_completion_clone, name='job_completion_clone'),
    path('api/job_delete/<int:pk>/', views.job_completion_delete, name='job_completion_delete'),
    path('job_completion_pdf/<int:pk>/', views.job_completion_pdf, name='job_completion_pdf'),
    path('api/clone_job/<int:pk>/', views.clone_job_completion, name='clone_job'),
    path('job_completion_list', views.job_completion_list, name="job_completion_list"),
    
    
    
    
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
   
    #path('', views.drinkWaterForm, name= ""),
] 
# if settings.DEBUG:
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


