# Generated by Django 4.1.1 on 2025-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('city_location', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_report_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_date', models.CharField(blank=True, max_length=100, null=True)),
                ('report_1', models.CharField(blank=True, max_length=100, null=True)),
                ('report_2', models.CharField(blank=True, max_length=100, null=True)),
                ('attention_1', models.CharField(blank=True, max_length=100, null=True)),
                ('attention_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_id_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_id_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_col_date', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_des_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_des_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_method_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_method_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_type_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_type_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_tech_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_tech_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample_col_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_analysis', models.CharField(blank=True, max_length=100, null=True)),
                ('test_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_water_1', models.CharField(blank=True, max_length=100, null=True)),
                ('wastewater_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sludge_1', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_water_2', models.CharField(blank=True, max_length=100, null=True)),
                ('wastewater_2', models.CharField(blank=True, max_length=100, null=True)),
                ('sludge_2', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_water_3', models.CharField(blank=True, max_length=100, null=True)),
                ('wastewater_3', models.CharField(blank=True, max_length=100, null=True)),
                ('sludge_3', models.CharField(blank=True, max_length=100, null=True)),
                ('inlet', models.JSONField(default=dict)),
                ('outlet', models.JSONField(default=dict)),
                ('test', models.JSONField(default=dict)),
                ('extra_field', models.JSONField(default=dict)),
                ('extra_field_2', models.JSONField(default=dict)),
                ('extra_field_3', models.JSONField(default=dict)),
                ('extra_field_3_1', models.JSONField(default=dict)),
                ('extra_field_4', models.JSONField(default=dict)),
                ('extra_field_4_1', models.JSONField(default=dict)),
                ('extra_field_5', models.JSONField(default=dict)),
                ('extra_field_6', models.JSONField(default=dict)),
                ('extra_field_7', models.JSONField(default=dict)),
                ('extra_field_8', models.JSONField(default=dict)),
                ('extra_field_8_1', models.JSONField(default=dict)),
                ('extra_field_9', models.JSONField(default=dict)),
                ('extra_field_10', models.JSONField(default=dict)),
                ('extra_field_11', models.JSONField(default=dict)),
                ('extra_field_12', models.JSONField(default=dict)),
                ('extra_field_13', models.JSONField(default=dict)),
                ('extra_field_14', models.JSONField(default=dict)),
                ('extra_field_15', models.JSONField(default=dict)),
                ('extra_field_16', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
