# Generated by Django 4.1.1 on 2025-07-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnviTechAlApp', '0182_ambientair2_pdf_desc_1_ambientair2_pdf_desc_2_and_more'),
        ('detox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detox',
            name='analyst_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_reports_detox', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='detox',
            name='assistant_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reports_detox', to='EnviTechAlApp.signatures'),
        ),
        migrations.AddField(
            model_name='detox',
            name='lab_manager_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_manager_reports_detox', to='EnviTechAlApp.signatures'),
        ),
    ]
