# Generated by Django 4.1.1 on 2025-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detox', '0002_detox_analyst_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detox',
            name='doc_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='doc_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='doc_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='edit_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='extra_field_17',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
