# Generated by Django 4.1.1 on 2025-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detox', '0003_detox_doc_1_detox_doc_2_detox_doc_3_detox_edit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detox',
            name='pdf_desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_desc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_desc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_desc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_heading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_image_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_image_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_image_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_image_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_image_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='pdf_image_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
