# Generated by Django 4.1.1 on 2025-08-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detox', '0004_detox_pdf_desc_1_detox_pdf_desc_2_detox_pdf_desc_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detox',
            name='date_analysis_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detox',
            name='legend_12',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
